// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 500 --nesting 4 --seed 6 --watchdog 25 --enable-file .simplify/simplify-control.txt
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000010000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000100000000000000000
//0000000000000000000000010000000000000000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

int watchdog_done = 0;

void *watchdog_func(void *x)
{
	for(int j=0;j<25;j++) {
		sleep(1);
		if (watchdog_done) {
			return NULL;
		}
	}
	printf("Watchdog timer expired (25 seconds)\n");
}


void func437(int *a)
{
}
void func312(int *a)
{
    #pragma oss task out(a[643;27]) node(2) label("func437")
    func437(a);
}
void func468(int *a)
{
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

	pthread_t watchdog;
	if (pthread_create(&watchdog, NULL, watchdog_func, NULL)) {
		return 1;
	}

    #pragma oss task out(a[297;518]) node(2) label("func312")
    func312(a);
    
    #pragma oss task weakout(a[514;331]) node(2) wait label("func468")
    func468(a);
    
    #pragma oss taskwait
    

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));
     watchdog_done = 1;
    pthread_join(watchdog, NULL);

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 500 --nesting 4 --seed 6 --watchdog 25 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
