// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 30 --nesting 3 --seed 11 --wait-clause --no-taskwaitnoflush --no-taskwaiton --enable-file simplify-control.txt
//0000000000000000001110000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>

void func15(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
   b[573] = 1573;
   b[574] = 1574;
   sleep(2);
}

void func14(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);

    #pragma oss task inout(b[573;2]) node(0) label("inner-nowait0")
    func15(b);

	// #pragma oss taskwait
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

	for(int j=0; j<1000; j++) {
    	b[j] = j;
	}

    #pragma oss task inout(b[573;2]) node(1) label("outer-wait1") wait
    func14(b);
    
    #pragma oss taskwait

	int fail = 0;
	for(int j=508;j<508+71;j++) {
		int ref = (j == 573 || j == 574) ? (1000+j) : j;
		if (b[j] != ref) {
			printf("b[%d] = %d (ref=%d)\n", j, b[j], ref);
			fail = 1;
		}
	}

#if 0
	for(int j=508;j<508+71;j++) {
		int ref = (j == 573 || j == 574) ? (1000+j) : j;
		assert (b[j] == ref);
	}
#endif

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

	if (!fail) { 
		printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 30 --nesting 3 --seed 11 --wait-clause --no-taskwaitnoflush --no-taskwaiton --enable-file simplify-control.txt]\n");
	} else {
		printf("Test failed!\n");
	}
	
    return(0);
}
	
