// Generated by ./nasty.py --nodes 3 --tasks 11 --nesting 3 --seed 145

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void func2(int *b)
{
}
void func3(int *b)
{
}
void func1(int *a,int *b)
{
    #pragma oss task in(b[896;11]) node(2) label("func2")
    func2(b);

    #pragma oss task weakin(b[896;11]) node(2) label("func3")
    func3(b);

}
void func5(int *b)
{
}
void func6(int *a,int *b)
{
}
void func4(int *a,int *b)
{
    #pragma oss task in(b[896;11]) node(1) label("func5")
    func5(b);

    #pragma oss taskwait on(a[390;2])

    #pragma oss task in(b[896;11]) node(1) label("func6")
    func6(a,b);

}
void func0(int *a,int *b)
{
    #pragma oss task in(b[896;11]) node(0) label("func1")
    func1(a,b);

    #pragma oss taskwait

    #pragma oss task weakout(a[390;2]) weakinout(b[896;11]) node(1) label("func4")
    func4(a,b);

}
void func9(int *b)
{
}
void func10(int *b)
{
}
void func8(int *b)
{
    #pragma oss task weakin(b[849;1]) in(b[846;3]) in(b[843;2]) node(1) label("func9")
    func9(b);

    #pragma oss taskwait

    func10(b);
}

void func7(int *a,int *b)
{
    #pragma oss taskwait on(b[862;1]) // returned OK

    #pragma oss task in(b[841;9]) node(1) label("func8") // none of this is returned
    func8(b);

}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));
	printf("a: %p\n", a);
	printf("b: %p\n", b);

    #pragma oss task inout(b[890;30]) weakout(a[185;219]) node(1) label("func0")
    func0(a,b);

	// b[938;1] returned
	// b[839;2] returned
    // #pragma oss task out(b[938;1]) weakout(a[33;845]) weakinout(b[839;30]) node(1) label("func7")
    #pragma oss task out(b[938;1]) weakout(a[33;845]) weakinout(b[839;2]) weakinout(b[841;28]) node(1) label("func7")
    func7(a,b);

    #pragma oss taskwait


	nanos6_dfree(a, 1000 * sizeof(int));
	nanos6_lfree(b, 1000 * sizeof(int));


    printf("Test passed [./nasty.py --nodes 3 --tasks 11 --nesting 3 --seed 145]\n");

    return(0);
}
