// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 95 --nesting 4 --seed 19 --watchdog 45 --enable-file .simplify/simplify-control.txt
//11110101000000000000000000000000000001100000000000000110000000000000000000000000
//0000000000001000000000000000001000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

void func4(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 2);
}
void func2(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    #pragma oss task weakinout(b[567;1]) node(2) label("func4")
    func4(b);
    
}
void func1(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    #pragma oss taskwait on(b[567;1])
    
    #pragma oss task inout(b[567;1]) node(0) wait label("func2")
    func2(b);
    
}
void func27(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 2);
}
void func0(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    #pragma oss task in(b[542;25]) weakout(b[567;1]) in(b[579;12]) node(1) label("func1")
    func1(b);
    
    #pragma oss taskwait
    
    #pragma oss task in(b[547;4]) weakin(b[599;2]) inout(b[551;6]) node(2) wait label("func27")
    func27(b);
    
}
void func40(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 2);
    #pragma oss taskwait on(b[492;24])
    
}
void func80(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 2);
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    // #pragma oss taskwait on(b[486;126])
    
    #pragma oss task weakinout(b[486;85]) in(b[576;36]) node(0) label("func0")
    func0(b);
    
    #pragma oss taskwait on(a[612;161])
    
    #pragma oss task weakout(a[244;268]) weakin(a[612;149]) weakout(a[761;160]) weakinout(b[486;81]) node(2) label("func40")
    func40(a,b);
    
    #pragma oss task weakin(a[612;149]) weakinout(b[486;81]) node(2) wait label("func80")
    func80(a,b);
    
    #pragma oss taskwait
    

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 95 --nesting 4 --seed 19 --watchdog 45 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
