// Generated by ./nasty.py --nodes 2 --tasks 15 --nesting 5 --seed 147

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void func4(int *b)
{
}
void func5(int *b)
{
}
void func3(int *b)
{
    #pragma oss task weakin(b[929;1]) weakin(b[900;1]) weakin(b[901;1]) weakin(b[902;1]) node(1) label("func4")
    func4(b);

    #pragma oss task weakin(b[899;1]) in(b[929;1]) weakin(b[900;2]) node(1) label("func5")
    func5(b);

}
void func7(int *b)
{
}
void func8(int *b)
{
}
void func6(int *b)
{
    // #pragma oss taskwait on(b[899;1])

    #pragma oss task weakin(b[900;1]) in(b[903;1]) weakin(b[929;1]) node(0) label("func7")
    func7(b);

    #pragma oss task weakin(b[898;3]) weakin(b[903;1]) node(1) label("func8")
    func8(b);

}
void func2(int *b)
{
    #pragma oss task in(b[929;1]) in(b[899;4]) node(0) label("func3")
    func3(b);

    #pragma oss task in(b[929;1]) in(b[903;1]) weakin(b[898;3]) node(1) label("func6")
    func6(b);

}
void func11(int *b)
{
}
void func12(int *b)
{
}
void func10(int *b)
{
    #pragma oss taskwait on(b[883;1])

    #pragma oss task in(b[929;1]) weakin(b[883;1]) weakin(b[882;1]) node(0) label("func11")
    func11(b);

    #pragma oss task weakin(b[929;1]) in(b[883;1]) node(0) label("func12")
    func12(b);

}
void func14(int *b)
{
}
void func13(int *b)
{
    #pragma oss task weakin(b[929;1]) weakin(b[903;1]) weakin(b[882;1]) node(0) label("func14")
    func14(b);

}
void func9(int *b)
{
    #pragma oss task in(b[883;1]) weakin(b[929;1]) in(b[881;2]) node(0) label("func10")
    func10(b);

    #pragma oss task in(b[882;1]) weakin(b[903;5]) weakin(b[883;1]) in(b[929;1]) node(1) label("func13")
    func13(b);

}
void func1(int *b)
{
    #pragma oss task weakin(b[894;11]) weakin(b[879;14]) in(b[929;1]) node(1) label("func2")
    func2(b);

    #pragma oss task weakin(b[929;1]) in(b[898;10]) weakin(b[880;4]) node(0) label("func9")
    func9(b);
}

void func0(int *a,int *b)
{
    #pragma oss task weakin(b[875;33]) in(b[929;1]) node(1) label("func1")
    func1(b);
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task in(b[852;78]) weakinout(b[930;14]) out(a[739;16]) node(1) label("func0")
    func0(a,b);

    #pragma oss taskwait

	nanos6_dfree(a, 1000 * sizeof(int));
	nanos6_lfree(b, 1000 * sizeof(int));


    printf("Test passed [./nasty.py --nodes 2 --tasks 15 --nesting 5 --seed 147]\n");

    return(0);
}

