// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 1 --tasks 70 --nesting 4 --seed 8 --wait-clause --no-taskwaitnoflush --no-taskwaiton --watchdog 5 --enable-file simplify-control.txt
//01100000000001000001000001000000000000000000000000000000000000000000000000000000
//0000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>



int main(void)
{
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task weakin(b[900;1]) in(b[891;4]) node(0) label("sleep")
	{
		sleep(1);
    }
    
    #pragma oss task weakinout(b[892;8]) in(b[900;1]) node(0) label("wait") wait
	{
		#pragma oss task in(b[900;1]) node(0) label("inner")
		{
		}
	}
    
    #pragma oss taskwait

   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 1 --tasks 70 --nesting 4 --seed 8 --wait-clause --no-taskwaitnoflush --no-taskwaiton --watchdog 5 --enable-file simplify-control.txt]\n");
	
    return(0);
}
	
