/*
 * Copyright (C) 2022  Paul Capenter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


// Generated by ./nasty.py --nodes 2 --tasks 11 --nesting 4 --seed 166

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void show(const int *a, int n)
{
	printf("Show %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		printf("0x%08x\n", a[j]);
	}
}

void check(const int *a, const int *ref, int n, const char *name, int ofs)
{
	// printf("Check %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		if (a[j] != ref[j])
		{
			const char *eq = (a[j] == ref[j]) ? "==" : "!=";
			printf("%s[%d]: 0x%08x %s 0x%08x\n", name, ofs+j, a[j], eq, ref[j]);
			assert_that(a[j] == ref[j]);
		}
	}
}

void copy(int *a, const int *ref, int n)
{
	memcpy(a, ref, n * sizeof(int));
}

void check_hash(const int *a, int hash, int n, const char *name)
{
	int val = 0;
	for (int j=0; j<n; j++)
	{
		val ^= a[j];
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
	if (val != hash)
		printf("Error in %s\n", name);
	assert_that(val == hash);
}

void fill(int *a, int val, int n)
{
	for (int j=0; j<n; j++)
	{
		a[j] = val;
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
}


void func3(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    check_hash(&b[415], 0x74e0626c, 4, "check_6");
}
void func4(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check_hash(&b[413], 0x408dee11, 1, "check_7");
    check_hash(&b[399], 0x78d7dc87, 1, "check_8");
}
void func2(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check_hash(&b[399], 0x00003039, 2, "check_3");
    check_hash(&b[380], 0x62da1d55, 14, "check_4");
    #pragma oss taskwait on(b[384;2])

    #pragma oss task weakin(b[414;1]) weakin(b[385;5]) in(b[415;4]) weakin(b[399;2]) node(0) label("func3")
    func3(b);

    #pragma oss task weakin(b[416;3]) in(b[413;1]) in(b[399;1]) node(1) label("func4")
    func4(b);
    
}
void func6(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check_hash(&b[397], 0x257fd5a5, 5, "check_10");
}
void func7(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
}
void func5(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check_hash(&b[346], 0x0ad4ce6b, 11, "check_9");
    #pragma oss task in(b[397;5]) weakin(b[353;3]) weakin(b[412;2]) weakin(b[346;4]) node(1) label("func6")
    func6(b);

    #pragma oss taskwait

    check_hash(&b[346], 0x0ad4ce6b, 11, "check_12");
    #pragma oss task weakin(b[414;1]) weakin(b[398;4]) node(1) label("func7")
    func7(b);

}
void func1(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    #pragma oss taskwait

    #pragma oss task weakin(b[413;6]) in(b[399;2]) in(b[380;14]) node(1) label("func2")
    func2(b);

    #pragma oss task weakin(b[392;14]) in(b[346;11]) weakin(b[412;3]) node(1) label("func5")
    func5(b);

}
void func10(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    check_hash(&b[361], 0x3e1e030c, 1, "check_21");
    check_hash(&b[685], 0x00003039, 2, "check_22");
    check_hash(&b[698], 0x03620191, 6, "check_23");
}
void func9(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    #pragma oss taskwait on(b[361;1])

    fill(&b[361], 0x66c6de3f, 1);
    #pragma oss taskwait

    check_hash(&b[361], 0x3e1e030c, 1, "check_17");
    #pragma oss taskwait on(b[682;5])

    fill(&b[682], 0x34a1244a, 5);
    fill(&b[698], 0x55fa0850, 6);
    #pragma oss task in(b[361;1]) in(b[685;2]) in(b[698;6]) node(0) label("func10")
    func10(b);
    
}
void func8(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    #pragma oss taskwait on(b[685;1])
    
    fill(&b[685], 0xdc4ded81, 1);
    #pragma oss task out(b[678;17]) out(b[360;9]) out(b[698;21]) node(1) label("func9")
    func9(b);
    
}
void func0(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    fill(&b[345], 0xa873b08c, 76);
    #pragma oss task weakin(b[345;76]) node(0) label("func1")
    func1(b);

    #pragma oss task weakinout(b[345;76]) out(b[676;63]) node(0) label("func8")
    func8(b);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    fill(&b[0], 0xae2c5ea7, 1000);

    #pragma oss task out(b[319;510]) weakout(a[845;8]) node(0) label("func0")
    func0(a,b);
    
    #pragma oss taskwait
    

	nanos6_dfree(a, 1000 * sizeof(int));
	nanos6_lfree(b, 1000 * sizeof(int));

    
    printf("Test passed [./nasty.py --nodes 2 --tasks 11 --nesting 4 --seed 166]\n");
	
    return(0);
}
	
