// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 80 --nesting 2 --seed 18 --watchdog 25 --enable-file .simplify/simplify-control.txt
//00010011000100000000000000000000000110011101000000000000000100000000000010011100
//0011111111100000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

void func61()
{
}
void func62(int *a,int *b)
{
}
void func63(int *a,int *b)
{
}
void func68(int *a)
{
}
void func69(int *a,int *b)
{
}
void func60(int *a,int *b)
{
    #pragma oss task  node(1) label("func61")
    func61();    // OK
    
    #pragma oss task in(b[130;1]) in(b[127;2]) weakin(a[632;39]) weakin(a[587;13]) if(0) label("func62")
    func62(a,b);
    
    #pragma oss task weakin(a[631;35]) out(a[141;10]) weakin(b[127;3]) node(2) label("func63")
    func63(a,b);
    
    #pragma oss task weakin(a[630;48]) weakin(a[550;17]) in(a[680;6]) weakin(a[587;1]) if(0) label("func68")
    func68(a);
    
    #pragma oss task weakin(b[131;1]) inout(a[138;1]) in(a[536;12]) in(a[683;1]) node(2) label("func69")
    func69(a,b);
    
}

void func72(int *a,int *b)
{
}
void func73(int *a)
{
}
void func74(int *a,int *b)
{
}
void func70(int *a,int *b)
{
    
    #pragma oss taskwait
    
    #pragma oss task weakin(b[182;2]) in(a[134;3]) inout(a[271;180]) weakout(b[180;1]) node(2) label("func72")
    func72(a,b);  // func72 doesn't wake up
    
    #pragma oss task weakin(a[271;180]) in(a[140;1]) node(0) wait label("func73")
    func73(a);
    
    #pragma oss task weakout(b[176;6]) weakinout(a[316;54]) node(2) wait label("func74")
    func74(a,b);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));
	printf("a: %p\n", a);
	printf("b: %p\n", b);

    // #pragma oss taskwait on(a[133;755])
    
    #pragma oss task inout(a[133;21]) in(a[535;69]) in(b[124;8]) weakin(a[626;64]) node(2) wait label("func60")
    func60(a,b); // OK
    
    func70(a,b);
    
    #pragma oss taskwait

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 80 --nesting 2 --seed 18 --watchdog 25 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
