// Generated by ./nasty.py --nodes 2 --tasks 75 --nesting 2 --seed 122

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>



void func27(int *a,int *b)
{
	printf("a\n");
}
void func28(int *a,int *b)
{
	printf("b\n");
}
void func29(int *a,int *b)
{
	printf("c\n");
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task inout(a[0;1]) weakin(b[0;64]) node(1) label("a")
    func27(a,b);
    
    #pragma oss task in(a[0;1]) weakin(b[0;64]) node(1) label("b")
    func28(a,b);
    
    #pragma oss task weakin(b[0;64]) node(1) label("c")
    func29(a,b);
    
    #pragma oss taskwait

	nanos6_dfree(a, 1000 * sizeof(int));
	nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [./nasty.py --nodes 2 --tasks 75 --nesting 2 --seed 122]\n");
	
    return(0);
}
	
