// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 1000 --nesting 2 --seed 18 --watchdog 25 --enable-file .simplify/simplify-control.txt
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00010000000000000000000000000000000000000000000000000000000000000000000000111111
//01101000000110000001000100100100000000000000000000000000000000000000000000000000
//00000000000000000001111111100111000101001001101110011100000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

int watchdog_done = 0;

void *watchdog_func(void *x)
{
	for(int j=0;j<25;j++) {
		sleep(1);
		if (watchdog_done) {
			return NULL;
		}
	}
	printf("Watchdog timer expired (25 seconds)\n");
	assert_that(0);
}


void func298(int *b)
{
}
void func299(int *a,int *b)
{
}
void func301(int *a)
{
}
void func302(int *a,int *b)
{
}
void func304(int *b)
{
}
void func311(int *a,int *b)
{
}
void func312(int *a,int *b)
{
}
void func319(int *b)
{
}
void func323(int *a,int *b)
{
}
void func326(int *a)
{
}
void func329(int *a,int *b)
{
}
void func297(int *a,int *b)
{
    #pragma oss task inout(b[868;22]) inout(b[893;10]) node(0) label("func298")
    func298(b);
    
    #pragma oss task out(b[900;1]) out(a[927;4]) out(a[369;8]) node(0) wait label("func299")
    func299(a,b);
    
    // #pragma oss taskwait on(a[235;119])
    
    #pragma oss task out(a[930;1]) out(a[183;139]) in(a[322;22]) node(0) wait label("func301")
    func301(a);
    
    #pragma oss task weakout(b[880;9]) in(a[327;17]) node(1) wait label("func302")
    func302(a,b);
    
    #pragma oss task weakinout(b[822;58]) weakinout(b[904;1]) node(1) label("func304")
    func304(b);
    
    #pragma oss task inout(a[161;22]) weakout(a[183;112]) weakout(b[894;3]) node(0) wait label("func311")
    func311(a,b);
    
    #pragma oss task inout(b[831;1]) weakout(b[832;29]) out(a[303;62]) node(0) wait label("func312")
    func312(a,b);
    
    #pragma oss task weakinout(b[813;15]) weakin(b[897;2]) node(0) wait label("func319")
    func319(b);
    
    #pragma oss task weakout(a[356;10]) weakinout(b[897;3]) node(0) label("func323")
    func323(a,b);
    
    #pragma oss task weakin(a[819;1]) in(a[933;1]) weakout(a[217;80]) node(0) label("func326")
    func326(a);
    
    #pragma oss task out(b[843;47]) in(a[933;1]) in(b[823;5]) in(a[161;18]) node(1) wait label("func329")
    func329(a,b);
    
}
void func397()
{
}
void func398(int *a)
{
}
void func399(int *b)
{
}
void func400(int *a)
{
}
void func401()
{
}
void func404(int *a)
{
}
void func405(int *a)
{
}
void func406(int *b)
{
}
void func410()
{
}
void func412()
{
}
void func415(int *a)
{
}
void func418(int *a)
{
}
void func419(int *a,int *b)
{
}
void func421(int *a,int *b)
{
}
void func422(int *b)
{
}
void func423(int *a)
{
}
void func426(int *a,int *b)
{
}
void func427(int *a)
{
}
void func428(int *a,int *b)
{
}
void func396(int *a,int *b)
{
    #pragma oss taskwait noflush
    
    #pragma oss taskwait noflush
    
    #pragma oss task  node(0) label("func397")
    func397();
    
    #pragma oss task out(a[298;15]) node(0) label("func398")
    func398(a);
    
    #pragma oss task out(b[757;40]) node(1) wait label("func399")
    func399(b);
    
    #pragma oss task weakout(a[166;64]) node(0) label("func400")
    func400(a);
    
    #pragma oss task  if(0) label("func401")
    func401();
    
    #pragma oss task out(a[297;37]) node(0) label("func404")
    func404(a);
    
    #pragma oss task weakout(a[220;5]) node(1) label("func405")
    func405(a);
    
    #pragma oss task weakout(b[806;1]) node(0) wait label("func406")
    func406(b);
    
    #pragma oss task  node(1) label("func410")
    func410();
    
    #pragma oss task  node(1) label("func412")
    func412();
    
    #pragma oss task out(a[347;21]) node(1) label("func415")
    func415(a);
    
    #pragma oss task weakout(a[302;35]) node(1) label("func418")
    func418(a);
    
    #pragma oss task weakout(a[183;31]) weakout(b[748;30]) node(1) label("func419")
    func419(a,b);
    
    #pragma oss task in(b[797;6]) weakout(a[300;51]) node(1) label("func421")
    func421(a,b);
    
    #pragma oss task weakinout(b[797;9]) node(0) label("func422")
    func422(b);
    
    #pragma oss task weakout(a[226;11]) out(a[170;42]) node(1) label("func423")
    func423(a);
    
    #pragma oss task out(a[308;70]) out(a[378;18]) weakin(b[797;4]) node(0) wait label("func426")
    func426(a,b);
    
    #pragma oss task weakout(a[392;11]) node(0) wait label("func427")
    func427(a);
    
    #pragma oss task out(a[153;43]) weakin(b[797;1]) node(1) label("func428")
    func428(a,b);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

	pthread_t watchdog;
	if (pthread_create(&watchdog, NULL, watchdog_func, NULL)) {
		return 1;
	}
    
    #pragma oss task out(a[161;224]) weakinout(b[807;98]) out(a[801;133]) node(1) wait label("func297")
    func297(a,b);
    
    #pragma oss task out(b[743;67]) weakout(a[114;124]) weakout(a[238;166]) node(1) label("func396")
    func396(a,b);
    
    #pragma oss taskwait
    

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));
     watchdog_done = 1;
    pthread_join(watchdog, NULL);

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 1000 --nesting 2 --seed 18 --watchdog 25 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
