// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --watchdog 6 --nodes 2 --tasks 500 --nesting 3 --seed 2 --enable-file simplify-control.txt
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00001000000000000000000000000000000000000000000000000000000111010001010000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//000000000000000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>
#include <time.h>

void func120(int *b)
{
#if 1
	struct timespec req;
	req.tv_sec = 0;
	req.tv_nsec = 1000;
	nanosleep(&req, NULL);
#endif
}
void func121(int *b)
{
}
void func122(int *b)
{
}
void func126(int *b)
{
}

void func119(int *b)
{
    #pragma oss task inout(b[560;1]) node(0) label("a")
    func120(b);
    
    #pragma oss task in(b[539;11]) node(1) label("b")
    func121(b);
    
    #pragma oss task weakin(b[539;5]) node(1) label("c")
    func122(b);
}
void func128(int *b)
{
}
void func73(int *b)
{
    #pragma oss task weakin(b[526;26]) inout(b[552;26]) node(1) label("e")
    func119(b);
    
    // the bad access is b[539;5] from C
    // #pragma oss task weakinout(b[630;7]) weakout(b[534;11]) weakin(b[566;12]) node(1) label("f")
    #pragma oss task weakout(b[534;11]) weakin(b[566;12]) node(1) label("f")
    func128(b);
}


int main(void)
{
	int *b = nanos6_lmalloc(1000 * sizeof(int));
	printf("Address of b = %p\n", b);

    func73(b);
    
    #pragma oss taskwait
    
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --watchdog 6 --nodes 2 --tasks 500 --nesting 3 --seed 2 --enable-file simplify-control.txt]\n");
	
    return(0);
}
	
