// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 90 --nesting 2 --seed 2 --watchdog 25 --enable-file .simplify/simplify-control.txt
//00000000000000000000000011000000010000000000000000000000000010001000000110101100
//000010010000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>


void func26(int *b)
{
}
void func20(int *b)
{
    #pragma oss task in(b[529;11]) node(0) label("func26")
    func26(b);
    
}
void func54(int *a,int *b)
{
}
void func59(int *b)
{
}
void func50(int *a,int *b)
{
    #pragma oss task out(a[807;11]) weakin(b[881;8]) in(b[889;30]) node(0) label("func54")
    func54(a,b);
    
    #pragma oss task weakout(b[131;211]) out(b[342;107]) node(2) wait label("func59")
    func59(b);
    
}
void func61(int *b)
{
}
void func63(int *a,int *b)
{
}
void func60(int *a,int *b)
{
    #pragma oss task in(b[635;2]) out(b[188;116]) inout(b[549;1]) weakin(b[644;3]) node(2) label("func61")
    func61(b);
    
    #pragma oss task out(b[549;1]) weakin(b[645;1]) out(a[744;52]) weakin(b[550;1]) node(2) wait label("func63")
    func63(a,b);
    
    #pragma oss taskwait noflush
    
}
void func72(int *a)
{
}
void func70(int *a)
{
    #pragma oss task weakout(a[800;65]) node(1) wait label("func72")
    func72(a);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));
	printf("a: %p\n", a);
	printf("b: %p\n", b);

    // #pragma oss taskwait on(b[634;220])
    
    #pragma oss task weakinout(b[289;262]) weakout(b[976;21]) node(0) wait label("func20")
    func20(b);
    
    #pragma oss task weakin(b[863;62]) out(a[5;924]) out(b[117;431]) node(2) label("func50")
    func50(a,b);
    
    #pragma oss task weakin(b[634;13]) inout(b[548;3]) out(a[423;485]) out(b[168;165]) node(0) label("func60")
    func60(a,b);
    
    #pragma oss task weakout(a[790;167]) node(0) wait label("func70")
    func70(a);
    
    #pragma oss taskwait
    

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 90 --nesting 2 --seed 2 --watchdog 25 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
