// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --track b[406] --no-hash --nodes 3 --tasks 85 --nesting 3 --seed 12 --watchdog 45 --enable-file .simplify/simplify-control.txt
//00000000000000000000000000000000000000100000000000000000000000000000000000000100
//000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

void func31(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
   b[406] = 2;
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

	printf("b: %p    &b[406]: %p\n", b, &b[406]);
    b[406] = 1;

    #pragma oss task out(b[167;355]) node(1) wait label("func31")
    func31(b);
    
    #pragma oss taskwait
	printf("after first taskwait\n");
	assert_that(b[406] == 2);
	b[406] = 3;
    
    #pragma oss taskwait
	printf("after second taskwait\n");
    
    assert_that(b[406] == 3);

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --track b[406] --no-hash --nodes 3 --tasks 85 --nesting 3 --seed 12 --watchdog 45 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
