// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 60 --nesting 2 --seed 12 --watchdog 25 --enable-file .simplify/simplify-control.txt
//100011000000000000000010001111001100001011000000000000110000010000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

int watchdog_done = 0;

void *watchdog_func(void *x)
{
	for(int j=0;j<25;j++) {
		sleep(1);
		if (watchdog_done) {
			return NULL;
		}
	}
	printf("Watchdog timer expired (25 seconds)\n");
}


void func22(int *b)
{
}
void func23(int *b)
{
}
void func25(int *b)
{
}
void func18(int *b)
{
    #pragma oss task weakout(b[296;222]) node(0) wait label("func22")
    func22(b);
    
    // #pragma oss task out(b[441;227]) node(0) label("func23")
	// does not get read or write satisfiability for b[441;77]
    #pragma oss task out(b[441;77]) node(0) label("func23")
    func23(b);
    
    #pragma oss task weakout(b[214;362]) node(0) label("func25")
    func25(b);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

	printf("a: %p\nb: %p\n", a,b);

	pthread_t watchdog;
	if (pthread_create(&watchdog, NULL, watchdog_func, NULL)) {
		return 1;
	}
    
    #pragma oss task weakout(b[173;506]) node(1) label("func18")
    func18(b);
    
    #pragma oss taskwait
    

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));
     watchdog_done = 1;
    pthread_join(watchdog, NULL);

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 60 --nesting 2 --seed 12 --watchdog 25 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
