// Generated by ./nasty.py --nodes 3 --tasks 1 --nesting 2 --seed 131

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void show(const int *a, int n)
{
	printf("Show %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		printf("0x%08x\n", a[j]);
	}
}

void check(const int *a, const int *ref, int n, const char *name, int ofs)
{
	// printf("Check %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		if (a[j] != ref[j])
		{
			const char *eq = (a[j] == ref[j]) ? "==" : "!=";
			printf("%s[%d]: 0x%08x %s 0x%08x\n", name, ofs+j, a[j], eq, ref[j]);
			assert_that(a[j] == ref[j]);
		}
	}
}

void copy(int *a, const int *ref, int n)
{
	memcpy(a, ref, n * sizeof(int));
}

void check_hash(const int *a, int hash, int n, const char *name)
{
	int val = 0;
	for (int j=0; j<n; j++)
	{
		val ^= a[j];
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
	if (val != hash)
		printf("Error in %s\n", name);
	assert_that(val == hash);
}

void fill(int *a, int val, int n)
{
	for (int j=0; j<n; j++)
	{
		a[j] = val;
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
}


void func0(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    fill(&b[0], 0xc34174bc, 1000);

    // #pragma oss taskwait on(b[489;477])
    
    // #pragma oss taskwait
    
    check_hash(&b[489], 0x6e6010be, 477, "check_3");
    #pragma oss taskwait on(b[926;28])
    
    fill(&b[926], 0x2f4c1c84, 28);
    #pragma oss task weakinout(b[489;171]) weakout(b[865;128]) weakout(b[21;347]) node(1) label("func0")
    func0(b);
    
    #pragma oss taskwait
    
    check_hash(&b[489], 0x37a70c50, 376, "check_6");

	nanos6_dfree(a, 1000 * sizeof(int));
	nanos6_lfree(b, 1000 * sizeof(int));

    
    printf("Test passed [./nasty.py --nodes 3 --tasks 1 --nesting 2 --seed 131]\n");
	
    return(0);
}
	
