// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 50 --nesting 2 --seed 9 --no-taskwaiton --no-taskwaitnoflush --enable-file simplify-control.txt
//000000000010000111000000000000000000000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void func11(int *b)
{
}
void func12(int *b)
{
}
void func13(int *b)
{
}

void func8(int *b)
{
    #pragma oss task weakin(b[673;4]) node(2) label("func11")
    func11(b);

    #pragma oss task weakin(b[673;4]) node(2) label("func12")
    func12(b);

    #pragma oss task weakin(b[673;4]) node(2) label("func13")
    func13(b);
}


int main(void)
{
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task weakin(b[673;4]) node(1) label("func8")
    func8(b);

    #pragma oss taskwait

   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 50 --nesting 2 --seed 9 --no-taskwaiton --no-taskwaitnoflush --enable-file simplify-control.txt]\n");

    return(0);
}

