// Generated by ../unit_tests_ompss_cluster/nasty.py --nodes 2 --tasks 45 --nesting 2 --seed 126

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>

void func0(int *b)
{
}

void func16(int *b)
{
}

void func24(int *b)
{
}


int main(void)
{
	int *b = nanos6_lmalloc(1000 * sizeof(int));
	printf("b: %p\n", b);
	printf("b[619]...b[625]: %p + %d\n", &b[619], 6*4);
	printf("&b[625]: %p\n", &b[625]);
	printf("&b[657]: %p\n", &b[657]);

    #pragma oss task out(b[619;72]) node(1) label("a")
    func0(b);
    
    #pragma oss task weakout(b[625;48]) node(0) label("b")
    func16(b);
    
    // #pragma oss task weakout(b[657;212]) node(1)
    #pragma oss task weakout(b[657;34]) node(1) label("c")
    func24(b);
    
    
    #pragma oss taskwait
	printf("B\n");
    

	nanos6_lfree(b, 1000 * sizeof(int));

    
    printf("Test passed [../unit_tests_ompss_cluster/nasty.py --nodes 2 --tasks 45 --nesting 2 --seed 126]\n");
	
    return(0);
}
	
