// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 1 --tasks 55 --nesting 2 --seed 4 --no-taskwaiton --no-taskwaitnoflush --enable-file simplify-control.txt
//0000000000000000000000000000001000000000000000000001010100010110000010


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>



void func41(int *b)
{
}
void func42(int *b)
{
}
void func46(int *b)
{
}
void func40(int *b)
{
    #pragma oss task weakout(b[827;1]) inout(b[826;1]) out(b[890;45]) node(0) label("func41")
    func41(b);

    #pragma oss task weakinout(b[826;1]) node(0) label("func42")
    func42(b);

    #pragma oss task weakout(b[924;11]) node(0) label("func46")
    func46(b);

}
void func49()
{
}
void func53(int *b)
{
}
void func48(int *b)
{
    #pragma oss task  if(0) label("func49")
    func49();

    #pragma oss task in(b[826;1]) node(0) label("func53")
    func53(b);

}


int main(void)
{
	int *b = nanos6_lmalloc(1000 * sizeof(int));

   // #pragma oss taskwait

    #pragma oss task weakout(b[878;57]) weakinout(b[826;2]) node(0) label("func40")
    func40(b);

    #pragma oss task weakin(b[826;1]) node(0) label("func48")
    func48(b);

    #pragma oss taskwait

   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 1 --tasks 55 --nesting 2 --seed 4 --no-taskwaiton --no-taskwaitnoflush --enable-file simplify-control.txt]\n");

    return(0);
}

