// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 200 --nesting 2 --seed 11 --watchdog 15 --enable-file .simplify/simplify-control.txt
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000010000111010000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

int watchdog_done = 0;

void *watchdog_func(void *x)
{
	for(int j=0;j<15;j++) {
		sleep(1);
		if (watchdog_done) {
			return NULL;
		}
	}
	printf("Watchdog timer expired (15 seconds)\n");
	assert_that(0);
}


void show(const int *a, int n)
{
	printf("Show %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		printf("0x%08x\n", a[j]);
	}
}

void check(const int *a, const int *ref, int n, const char *name, int ofs)
{
	// printf("Check %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		if (a[j] != ref[j])
		{
			const char *eq = (a[j] == ref[j]) ? "==" : "!=";
			printf("%s[%d]: 0x%08x %s 0x%08x\n", name, ofs+j, a[j], eq, ref[j]);
			assert_that(a[j] == ref[j]);
		}
	}
}

void copy(int *a, const int *ref, int n)
{
	memcpy(a, ref, n * sizeof(int));
}

void check_hash(const int *a, int hash, int n, const char *name)
{
	int val = 0;
	for (int j=0; j<n; j++)
	{
		val ^= a[j];
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
	if (val != hash)
		printf("Error in %s\n", name);
	assert_that(val == hash);
}

void fill(int *a, int val, int n)
{
	for (int j=0; j<n; j++)
	{
		a[j] = val;
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
}


void func93(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    check_hash(&a[115], 0x4f89a688, 4, "check_180");
}
void func94(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    fill(&a[115], 0xe1a38821, 7);
}
void func95(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check_hash(&b[989], 0x00003039, 2, "check_181");
}
void func97(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
}
void func90(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    fill(&a[115], 0x79ef6541, 4);
    #pragma oss task weakout(b[750;100]) in(a[115;4]) weakout(b[574;104]) node(0) label("func93")
    func93(a,b);
    
    #pragma oss task out(a[115;7]) weakout(a[122;2]) weakin(b[988;3]) node(0) wait label("func94")
    func94(a,b);
    
    #pragma oss task in(b[989;2]) weakout(b[942;6]) node(1) label("func95")
    func95(b);
    
    #pragma oss task weakinout(b[988;2]) node(1) wait label("func97")
    func97(b);
    
}

int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));


	pthread_t watchdog;
	if (pthread_create(&watchdog, NULL, watchdog_func, NULL)) {
		return 1;
	}
    fill(&b[0], 0x2bcf5b7a, 1000);

    #pragma oss task out(a[88;42]) weakout(b[521;427]) weakinout(b[987;5]) node(1) wait label("func90")
    func90(a,b);
    
    #pragma oss taskwait
    
    check_hash(&b[0], 0x6c722666, 19, "check_357");
    check_hash(&b[996], 0x06e55127, 1, "check_357");
    check_hash(&b[999], 0x0eca2c72, 1, "check_357");

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));
     watchdog_done = 1;
    pthread_join(watchdog, NULL);

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 200 --nesting 2 --seed 11 --watchdog 15 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
