// Generated by ./nasty.py --nodes 2 --tasks 6 --nesting 2 --seed 152

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void func1(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
}
void func2(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
}
void func0(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    
    #pragma oss task weakin(b[913;6]) node(0) label("a")
    func1(b);
    
    #pragma oss task weakinout(b[913;6]) node(0) label("b")
    func2(b);
    
	#pragma oss taskwait
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task weakout(b[913;6]) node(1) label("e")
    func0(b);
    
    #pragma oss taskwait
    
	nanos6_dfree(a, 1000 * sizeof(int));
	nanos6_lfree(b, 1000 * sizeof(int));
    
    printf("Test passed [./nasty.py --nodes 2 --tasks 6 --nesting 2 --seed 152]\n");
	
    return(0);
}
	
