// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 65 --nesting 10 --seed 2 --watchdog 5 --enable-file .simplify/simplify-control.txt
//10000000000000000000000000000000000000000000000000000000000000000000000000000000
//000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>


int watchdog_done = 0;

void *watchdog_func(void *x)
{
	for(int j=0;j<5;j++) {
		sleep(1);
		if (watchdog_done) {
			return NULL;
		}
	}
	printf("Watchdog timer expired (5 seconds)\n");
	assert_that(0);
}



void func0(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
}

int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));


	pthread_t watchdog;
	if (pthread_create(&watchdog, NULL, watchdog_func, NULL)) {
		return 1;
	}

    #pragma oss task weakout(b[159;199]) weakout(a[919;60]) node(0) label("func0")
    func0(a,b);
    
    #pragma oss taskwait
    

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));
     watchdog_done = 1;
    pthread_join(watchdog, NULL);

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 65 --nesting 10 --seed 2 --watchdog 5 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
