// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --watchdog 3 --nodes 2 --tasks 95 --nesting 3 --seed 5 --no-taskwaitnoflush --enable-file simplify-control.txt
//00000000000000000000000000000000000000000000000000000000000000000000000001000001
//00000000011000000010000010001010000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

int watchdog_done = 0;

void *watchdog_func(void *x)
{
	for(int j=0;j<3;j++) {
		sleep(1);
		if (watchdog_done) {
			return NULL;
		}
	}
	printf("Watchdog timer expired (3 seconds)\n");
	assert_that(0);
}


void show(const int *a, int n)
{
	printf("Show %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		printf("0x%08x\n", a[j]);
	}
}

void check(const int *a, const int *ref, int n, const char *name, int ofs)
{
	// printf("Check %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		if (a[j] != ref[j])
		{
			const char *eq = (a[j] == ref[j]) ? "==" : "!=";
			printf("%s[%d]: 0x%08x %s 0x%08x\n", name, ofs+j, a[j], eq, ref[j]);
			assert_that(a[j] == ref[j]);
		}
	}
}

void copy(int *a, const int *ref, int n)
{
	memcpy(a, ref, n * sizeof(int));
}

void check_hash(const int *a, int hash, int n, const char *name)
{
	int val = 0;
	for (int j=0; j<n; j++)
	{
		val ^= a[j];
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
	if (val != hash)
		printf("Error in %s\n", name);
	assert_that(val == hash);
}

void fill(int *a, int val, int n)
{
	for (int j=0; j<n; j++)
	{
		a[j] = val;
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
}


void func75(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check_hash(&b[959], 0x69fbf899, 5, "check_158");
}
void func81(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    check_hash(&b[964], 0x42bab6e6, 1, "check_174");
}
void func90(int *b)
{
    check_hash(&b[964], 0x00003039, 2, "check_192");
}
void func92(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
}
void func87(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    #pragma oss task in(b[964;2]) if(0) label("func90")
    func90(b);

    #pragma oss task weakin(b[965;1]) node(1) label("func92")
    func92(b);

}
void func62(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    #pragma oss taskwait on(b[959;7])

    fill(&b[959], 0x5185dc3c, 7);
    #pragma oss task inout(b[959;5]) node(1) label("func75")
    func75(b);

    #pragma oss task inout(b[964;1]) weakout(a[429;233]) node(0) label("func81")
    func81(a,b);

    #pragma oss task weakin(b[964;2]) node(1) label("func87")
    func87(b);

}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));


	pthread_t watchdog;
	if (pthread_create(&watchdog, NULL, watchdog_func, NULL)) {
		return 1;
	}
    fill(&b[0], 0xe48c2d9d, 1000);

    #pragma oss task weakout(a[310;452]) out(b[944;22]) node(1) label("func62")
    func62(a,b);

    #pragma oss taskwait


   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));
     watchdog_done = 1;
    pthread_join(watchdog, NULL);

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --watchdog 3 --nodes 2 --tasks 95 --nesting 3 --seed 5 --no-taskwaitnoflush --enable-file simplify-control.txt]\n");

    return(0);
}

