// Generated by /home/bsc28/bsc28600/work/20210906-impi/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 1000 --nesting 5 --seed 10 --watchdog 30 --no-all-region --enable-file .simplify/simplify-control.txt
//10100000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000010110010000000001000000000010010000000000000000011001000000000000111100010
//00000000000000000000000000100000000000000000000000000000000000000000000000000000
//00000000000111000000000001000000000100000000100001000000110110000000010100000000
//00000000011000000010110001000100100000000001000000000100010000000000000000010110
//00000101000000001011000010100000100000000000001001000000000000010000100011010000
//00000000000000000000011000000000000000000000000000000000000000000000000000000000
//00010110000000000000000000000000000000000000000001100000000000000000000000000000
//00000001000000000000100000000000000000000000000000000000000000000001010110000000
//00000000100000101100000011110010001001000000000000000000000000000010100000000100
//00000000000001110001100000000101101100000000000000000000000000000000000000000000
//000000000000000000000000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void func460(int *a)
{
    #pragma oss task for in(a[955;1]) chunksize(10) node(0) label("taskfor465")
       for(int i=0; i<1; i++) {
    }
}
void func474(int *a)
{
    #pragma oss task for out(a[427;1]) chunksize(4) node(2) label("taskfor475")
       for(int i=0; i<1; i++) {
            a[427+i] = 0x4a3e4b60;
    }
}
void func459(int *a)
{
    #pragma oss task in(a[955;1]) node(1) label("func460")
    func460(a);
    
    #pragma oss task weakout(a[427;1]) in(a[955;1]) node(2) label("func474")
    func474(a);
    
}
void func499(int *a,int *b)
{
    #pragma oss task for in(b[702;1]) chunksize(37) node(0) label("taskfor500")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task for out(a[442;1]) chunksize(71) node(0) label("taskfor501")
       for(int i=0; i<1; i++) {
            a[442+i] = 0x1dc38594;
    }
    #pragma oss task for in(b[702;1]) chunksize(92) node(2) label("taskfor502")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task for in(b[702;1]) chunksize(89) node(0) label("taskfor505")
       for(int i=0; i<1; i++) {
    }
}
void func490(int *a,int *b)
{
    #pragma oss task in(b[702;1]) weakout(a[442;1]) node(0) label("func499")
    func499(a,b);
    
}
void func586(int *b)
{
    #pragma oss task for in(b[702;1]) chunksize(50) node(1) label("taskfor589")
       for(int i=0; i<1; i++) {
    }
}
void func563(int *b)
{
    #pragma oss task for out(b[701;1]) chunksize(71) node(0) label("taskfor564")
       for(int i=0; i<1; i++) {
            b[701+i] = 0xebe3c075;
    }
    #pragma oss task for in(b[702;1]) chunksize(92) node(2) label("taskfor565")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task for in(b[702;1]) chunksize(23) node(1) label("taskfor572")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task for out(b[694;5]) chunksize(3) node(0) label("taskfor579")
       for(int i=0; i<5; i++) {
            b[694+i] = 0xa94eaf43;
    }
    #pragma oss task weakout(b[694;7]) weakin(b[702;1]) node(0) wait label("func586")
    func586(b);
    
}
void func458(int *a,int *b)
{
    #pragma oss task weakout(a[419;9]) weakout(a[428;5]) weakin(a[955;1]) node(0) wait label("func459")
    func459(a);
    
    #pragma oss task for out(b[702;3]) chunksize(79) node(0) label("taskfor488")
       for(int i=0; i<3; i++) {
            b[702+i] = 0xdaf2d4ae;
    }
    #pragma oss task for in(a[950;6]) chunksize(1) node(1) label("taskfor489")
       for(int i=0; i<6; i++) {
    }
    #pragma oss task weakout(a[441;2]) inout(b[702;1]) node(2) wait label("func490")
    func490(a,b);
    
    #pragma oss task for in(a[954;2]) chunksize(13) node(0) label("taskfor524")
       for(int i=0; i<2; i++) {
    }
    #pragma oss task weakin(b[702;1]) weakout(b[694;8]) node(2) wait label("func563")
    func563(b);
    
}
void func595(int *b)
{
    #pragma oss task for in(b[579;1]) chunksize(99) node(1) label("taskfor599")
       for(int i=0; i<1; i++) {
    }
}
void func614(int *b)
{
    #pragma oss task for in(b[579;1]) chunksize(16) node(2) label("taskfor618")
       for(int i=0; i<1; i++) {
    }
}
void func594(int *b)
{
    #pragma oss task weakin(b[740;1]) in(b[579;1]) node(0) wait label("func595")
    func595(b);
    
    #pragma oss task for in(b[734;1]) chunksize(98) node(0) label("taskfor601")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task for in(b[737;2]) chunksize(19) node(0) label("taskfor613")
       for(int i=0; i<2; i++) {
    }
    #pragma oss task weakin(b[579;1]) node(0) wait label("func614")
    func614(b);
    
}
void func621(int *b)
{
    #pragma oss task for out(b[643;4]) chunksize(1) node(2) label("taskfor624")
       for(int i=0; i<4; i++) {
            b[643+i] = 0x4c01f8ed;
    }
    #pragma oss task for out(b[638;5]) chunksize(4) node(0) label("taskfor626")
       for(int i=0; i<5; i++) {
            b[638+i] = 0x500dfa75;
    }
}
void func644(int *b)
{
    #pragma oss task for in(b[754;1]) chunksize(37) node(2) label("taskfor647")
       for(int i=0; i<1; i++) {
    }
}
void func620(int *b)
{
    #pragma oss task out(b[637;10]) node(0) wait label("func621")
    func621(b);
    
    #pragma oss task for out(b[640;6]) chunksize(6) node(2) label("taskfor628")
       for(int i=0; i<6; i++) {
            b[640+i] = 0x9501dd1d;
    }
    #pragma oss task for in(b[743;2]) chunksize(10) node(2) label("taskfor636")
       for(int i=0; i<2; i++) {
    }
    #pragma oss task weakin(b[754;1]) if(0) label("func644")
    func644(b);
    
}
void func694(int *b)
{
    #pragma oss task for in(b[579;1]) chunksize(34) node(2) label("taskfor697")
       for(int i=0; i<1; i++) {
    }
}
void func707(int *b)
{
    #pragma oss task for in(b[639;1]) chunksize(4) node(0) label("taskfor712")
       for(int i=0; i<1; i++) {
    }
}
void func686(int *b)
{
    #pragma oss task weakin(b[579;1]) node(0) label("func694")
    func694(b);
    
    #pragma oss task weakin(b[579;1]) in(b[639;1]) node(0) label("func707")
    func707(b);
    
}
void func593(int *b)
{
    #pragma oss task weakin(b[579;1]) in(b[727;12]) weakin(b[739;2]) node(1) label("func594")
    func594(b);
    
    #pragma oss task in(b[734;23]) weakout(b[616;31]) node(2) wait label("func620")
    func620(b);
    
    #pragma oss task weakin(b[579;1]) weakout(b[826;2]) out(b[613;28]) node(0) wait label("func686")
    func686(b);
    
}
void func732(int *a)
{
    #pragma oss task for in(a[948;1]) chunksize(76) node(1) label("taskfor733")
       for(int i=0; i<1; i++) {
    }
}
void func716(int *a)
{
    #pragma oss task weakin(a[948;1]) node(2) wait label("func732")
    func732(a);
    
}
void func773(int *a,int *b)
{
    #pragma oss taskwait on(b[768;1])
    
    #pragma oss task for inout(b[768;1]) chunksize(50) node(1) label("taskfor775")
       for(int i=0; i<1; i++) {
            b[768+i] ^= 0x3cbcfa50;
    }
}
void func803(int *a,int *b)
{
    #pragma oss task for in(a[948;1]) chunksize(89) node(0) label("taskfor824")
       for(int i=0; i<1; i++) {
    }
}
void func714(int *a,int *b)
{
    #pragma oss task for in(a[948;1]) chunksize(70) node(1) label("taskfor715")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task in(a[948;1]) node(0) label("func716")
    func716(a);
    
    #pragma oss task weakin(a[948;1]) weakout(b[768;1]) node(2) label("func773")
    func773(a,b);
    
    #pragma oss task for in(a[948;1]) chunksize(28) node(0) label("taskfor802")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task weakin(a[948;1]) out(b[764;4]) node(2) label("func803")
    func803(a,b);
    
}
void func859(int *a,int *b)
{
    #pragma oss task for in(b[584;1]) chunksize(79) node(2) label("taskfor860")
       for(int i=0; i<1; i++) {
    }
}
void func870(int *a,int *b)
{
    #pragma oss task for in(b[584;1]) chunksize(4) node(2) label("taskfor874")
       for(int i=0; i<1; i++) {
    }
}
void func876(int *a)
{
    #pragma oss task for in(a[952;1]) chunksize(42) node(0) label("taskfor877")
       for(int i=0; i<1; i++) {
    }
}
void func858(int *a,int *b)
{
    #pragma oss task weakin(b[584;1]) in(a[952;1]) weakin(a[951;1]) in(a[950;1]) node(1) label("func859")
    func859(a,b);
    
    #pragma oss task in(a[954;1]) in(a[951;2]) in(b[584;1]) node(0) wait label("func870")
    func870(a,b);
    
    #pragma oss task weakin(a[954;1]) in(a[952;1]) if(0) label("func876")
    func876(a);
    
}
void func886(int *a)
{
    #pragma oss task for in(a[954;1]) chunksize(44) node(0) label("taskfor889")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task for in(a[953;1]) chunksize(13) node(2) label("taskfor891")
       for(int i=0; i<1; i++) {
    }
}
void func910(int *a,int *b)
{
    #pragma oss task for in(a[954;1]) chunksize(57) node(2) label("taskfor911")
       for(int i=0; i<1; i++) {
    }
}
void func882(int *a,int *b)
{
    #pragma oss task for in(a[954;1]) chunksize(90) node(0) label("taskfor883")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task for in(a[954;1]) chunksize(70) node(0) label("taskfor884")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task for in(a[953;1]) chunksize(41) node(0) label("taskfor885")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task weakin(a[954;1]) in(a[953;1]) node(2) label("func886")
    func886(a);
    
    #pragma oss task in(a[954;1]) in(b[583;1]) weakin(a[953;1]) node(0) wait label("func910")
    func910(a,b);
    
}
void func927(int *a)
{
}
void func929(int *a)
{
}
void func930(int *a)
{
}
void func926(int *a)
{
    #pragma oss task in(a[952;1]) node(0) wait label("func927")
    func927(a);
    
    #pragma oss taskwait on(a[954;1])
    
    #pragma oss task in(a[952;1]) node(0) wait label("func929")
    func929(a);
    
    #pragma oss task weakin(a[952;1]) node(0) wait label("func930")
    func930(a);
    
}
void func937(int *a)
{
}
void func938(int *a)
{
}
void func939(int *a)
{
}
void func936(int *a)
{
    #pragma oss task in(a[954;1]) weakin(a[952;1]) node(2) wait label("func937")
    func937(a);
    
    #pragma oss taskwait noflush
    
    #pragma oss task in(a[952;1]) node(2) wait label("func938")
    func938(a);
    
    #pragma oss task weakin(a[952;1]) node(0) wait label("func939")
    func939(a);
    
}
void func917(int *a,int *b)
{
    #pragma oss task in(a[954;1]) in(a[952;1]) node(2) wait label("func926")
    func926(a);
    
    #pragma oss task weakin(a[952;1]) in(a[954;1]) if(0) label("func936")
    func936(a);
    
}
void func831(int *a,int *b)
{
    #pragma oss task for in(b[583;1]) chunksize(54) node(0) label("taskfor857")
       for(int i=0; i<1; i++) {
    }
    #pragma oss task weakin(b[584;1]) in(a[954;1]) weakin(a[950;3]) node(2) wait label("func858")
    func858(a,b);
    
    #pragma oss task in(b[583;1]) weakin(a[953;1]) in(a[954;1]) node(2) wait label("func882")
    func882(a,b);
    
    #pragma oss task in(a[952;1]) out(b[757;1]) weakin(a[954;1]) node(2) label("func917")
    func917(a,b);
    
}
void func457(int *a,int *b)
{
    #pragma oss task weakin(a[949;8]) out(a[364;72]) weakout(b[693;14]) out(a[436;7]) node(2) wait label("func458")
    func458(a,b);
    
    #pragma oss task for in(a[954;2]) chunksize(16) node(0) label("taskfor592")
       for(int i=0; i<2; i++) {
    }
    #pragma oss task weakin(b[710;51]) out(b[821;7]) weakout(b[603;82]) in(b[567;15]) node(0) wait label("func593")
    func593(b);
    
    #pragma oss task in(a[948;1]) weakout(a[395;43]) out(b[744;29]) weakout(b[569;14]) node(1) label("func714")
    func714(a,b);
    
    #pragma oss task out(b[722;47]) weakin(a[948;6]) in(a[954;1]) weakin(b[583;2]) node(0) label("func831")
    func831(a,b);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

	printf("namespacenewfail29: failed since at least 3a0bc014 Fix issues with WriteID\n");

    #pragma oss taskwait on(a[911;63])
    
    #pragma oss task for in(b[203;655]) chunksize(76) node(0) label("taskfor0")
       for(int i=0; i<655; i++) {
    }
    #pragma oss task in(a[940;17]) inout(b[558;36]) out(a[157;434]) weakinout(b[594;240]) node(0) wait label("func457")
    func457(a,b);
    
    #pragma oss taskwait
    

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20210906-impi/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 1000 --nesting 5 --seed 10 --watchdog 30 --no-all-region --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
