// Generated by /home/bsc28/bsc28600/work/20210906-impi/ompss-2-testgen/ompss-2-testgen --no-hash --nodes 3 --tasks 70 --nesting 3 --seed 11 --watchdog 30 --no-all-region --no-taskfor --enable-file .simplify/simplest.txt
//00000000000000000000000000001000000000000000000000001010101000000000000000000000
//0000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

void func38(int *b)
{
}

void func41(int *b)
{
}

void func37(int *b)
{
    #pragma oss task in(b[583;1]) node(2) label("func38")
    func38(b);
    
    #pragma oss taskwait
    
	b[583] = 2; 
    #pragma oss task weakinout(b[583;1]) node(2) label("func41")
    func41(b);
}

void func21(int *b)
{
    #pragma oss task inout(b[583;1]) node(0) label("func37")
    func37(b);
    
}

int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

	b[583] = 1;

    #pragma oss task weakinout(b[479;106]) node(2) wait label("func21")
    func21(b);
    
    #pragma oss taskwait
    
	assert_that(b[583] == 2);

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20210906-impi/ompss-2-testgen/ompss-2-testgen --no-hash --nodes 3 --tasks 70 --nesting 3 --seed 11 --watchdog 30 --no-all-region --no-taskfor --enable-file .simplify/simplest.txt]\n");
	
    return(0);
}
	
