// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 45 --nesting 4 --seed 6 --wait-clause --watchdog 5 --enable-file simplify-control.txt
//1000000000000000000001000000000000100100000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>


void func25(int *b)
{
}

void func23(int *b)
{
    #pragma oss task weakin(b[864;1]) node(0) label("func25")
    func25(b);
}

void func14(int *b)
{
    #pragma oss task weakin(b[864;1]) weakin(b[865;1]) node(0) wait label("func23")
    func23(b);
}

void func0(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    #pragma oss task out(b[862;10]) out(b[872;51]) node(0) label("func14")
    func14(b);
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task weakout(b[836;127]) node(1) wait label("func0")
    func0(b);
    
    #pragma oss taskwait

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 45 --nesting 4 --seed 6 --wait-clause --watchdog 5 --enable-file simplify-control.txt]\n");
	
    return(0);
}
	
