/*
 * Copyright (C) 2022  Paul Capenter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 1000 --nesting 2 --seed 2 --watchdog 45 --enable-file .simplify/simplify-control.txt
//01000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000001000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000001000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000100000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000001000000000000011000000000000000000
//0000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

void func976(char *all)
{
}
void func977(int *b)
{
}
void func963(char *all,int *b)
{
    #pragma oss task weakinout(all[1;-2]) weakinout(all[1;-2]) weakinout(all[1;-2]) node(0) label("func976")
    func976(all);
    
    #pragma oss task commutative(b[15;1]) commutative(b[16;2]) node(0) wait label("func977")
    func977(b);
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));
	char *all = (char *)NULL;

    #pragma oss taskwait on(a[158;788])
    
    #pragma oss task for out(a[793;90]) chunksize(49) node(0) label("taskfor224")
       for(int i=0; i<90; i++) {
    }
    #pragma oss task for in(a[230;14]) chunksize(13) node(0) label("taskfor349")
       for(int i=0; i<14; i++) {
    }
    #pragma oss task for inout(a[230;7]) chunksize(5) node(1) label("taskfor702")
       for(int i=0; i<7; i++) {
    }
    #pragma oss task weakinout(all[1;-2]) weakcommutative(b[14;4]) node(1) wait label("func963")
    func963(all,b);
    
    #pragma oss taskwait

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 1000 --nesting 2 --seed 2 --watchdog 45 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
