// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 90 --nesting 2 --seed 6 --watchdog 25 --enable-file .simplify/simplify-control.txt
//00010000101001011101001001010000000000000000000000000000000000000000000000000000
//000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>

void func6(int *b)
{
}

void func1(int *a,int *b)
{
    #pragma oss task in(b[423;34]) node(0) label("func6")
    func6(b);
}
void func20(char *all,int *b)
{
}
void func18(int *a,char *all,int *b)
{
    #pragma oss task weakinout(all[1;-2]) weakin(b[576;1]) node(0) wait label("func20")
    func20(all,b);
    
    #pragma oss taskwait
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));
	char *all = (char *)NULL;

    #pragma oss task weakout(a[642;78]) inout(b[212;124]) in(b[336;154]) weakinout(b[490;333]) node(1) label("func1")
    func1(a,b);
    
    #pragma oss task weakinout(all[1;-2]) in(b[574;3]) in(b[625;261]) out(a[734;64]) node(1) wait label("func18")
    func18(a,all,b);
    
    #pragma oss taskwait
   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 90 --nesting 2 --seed 6 --watchdog 25 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
