// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 8 --nesting 4 --seed 13 --watchdog 45 --enable-file .simplify/simplify-control.txt
//11000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>

void func1(char *all)
{
}
void func0(int *a,char *all)
{
    #pragma oss task weakinout(all[1;-2]) node(2) label("func1")
    func1(all);
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));
	char *all = (char *)NULL;

    #pragma oss task weakinout(all[1;-2]) weakout(a[61;690]) weakinout(all[1;-2]) label("func0")
    func0(a,all);
    
    #pragma oss taskwait
    
   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 8 --nesting 4 --seed 13 --watchdog 45 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
