// Generated by /home/bsc28/bsc28600/work/20210906-impi/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 500 --nesting 4 --seed 1427 --watchdog 45 --auto --enable-file .simplify/simplify-control.txt
//11000000000100000000000001101000100000000000100000000000101000000000101100110000
//00000010100011111011101011000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000001110001000000010000000000001100111100110101011000000000000000
//10100000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000111100111100000000000111110110000000000101111111
//01011000000000000000000010000000000000000000000000000010011011100000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000


#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

int watchdog_done = 0;

void *watchdog_func(void *x)
{
	for(int j=0;j<45;j++) {
		sleep(1);
		if (watchdog_done) {
			return NULL;
		}
	}
	printf("Watchdog timer expired (45 seconds)\n");
	assert(0);
}


void show(const int *a, int n)
{
	printf("Show %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		printf("0x%08x\n", a[j]);
	}
}

void check(const int *a, const int *ref, int n, const char *name, int ofs)
{
	// printf("Check %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		if (a[j] != ref[j])
		{
			const char *eq = (a[j] == ref[j]) ? "==" : "!=";
			printf("%s[%d]: 0x%08x %s 0x%08x\n", name, ofs+j, a[j], eq, ref[j]);
			assert(a[j] == ref[j]);
		}
	}
}

void copy(int *a, const int *ref, int n)
{
	memcpy(a, ref, n * sizeof(int));
}

void check_hash(const int *a, int hash, int n, const char *name)
{
	int val = 0;
	for (int j=0; j<n; j++)
	{
		val ^= a[j];
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
	if (val != hash)
		printf("Error in %s\n", name);
	assert(val == hash);
}

void fill(int *a, int val, int n)
{
	for (int j=0; j<n; j++)
	{
		a[j] = val;
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
}


int ref_0[2] = {
          0x1b347d84, 0x2bafd96d 
};
int ref_1[137] = {
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000, 0x00000000, 0x00000000, 0x00000000, 
          0x00000000 
};
int ref_2[1] = {
          0x468bec19 
};
int ref_3[105] = {
          0x3a61f74b, 0x04115528, 0x0843a241, 0x1f8213e6, 
          0x5656bd27, 0x63ba9bd4, 0x2be7217d, 0x414b8872, 
          0x4ae804c3, 0x480fa140, 0x69495879, 0x53c5b9be, 
          0x50bc2a1f, 0x27ed916c, 0x47fe0335, 0x7c1fb3ca, 
          0x5a83493b, 0x28d85858, 0x7b189db1, 0x516d4296, 
          0x0bd33e17, 0x42a6a204, 0x796863ed, 0x7632f222, 
          0x41c3a4b3, 0x71edda70, 0x5d7451e9, 0x3eb20e6e, 
          0x0949d90f, 0x252e2d9c, 0x493723a5, 0x6ff4a37a, 
          0x1f54f72b, 0x50be8788, 0x499b5521, 0x63997d46, 
          0x56a9db07, 0x55789434, 0x75b7225d, 0x1c6027d2, 
          0x7f7f20a3, 0x2624bfa0, 0x45c88759, 0x1774ef1e, 
          0x2cd923ff, 0x57a635cc, 0x5df14015, 0x667cdf2a, 
          0x73a6011b, 0x07e6e2b8, 0x48b2c891, 0x5e61c3f6, 
          0x7f9993f7, 0x47837264, 0x5d2a5ccd, 0x66de2982, 
          0x19c97893, 0x723750d0, 0x4d0cf8c9, 0x36c95bce, 
          0x7d090aef, 0x2208a9fc, 0x16635885, 0x092366da, 
          0x1405670b, 0x293469e8, 0x5505f801, 0x16e116a6, 
          0x7d2168e7, 0x3eda3c94, 0x2fd9133d, 0x6177f732, 
          0x7011ac83, 0x4a688e00, 0x5dc8a639, 0x1a2a547e, 
          0x61388ddf, 0x79c88a2c, 0x7e846cf5, 0x32133a8a, 
          0x7ec228fb, 0x0e4a1d18, 0x42fbe371, 0x5ef27556, 
          0x638059d7, 0x0c4ff2c4, 0x219a45ad, 0x20b890e2, 
          0x1b86bc73, 0x39bb7730, 0x12428fa9, 0x13d2d92e, 
          0x5686accf, 0x1718d65c, 0x0e0b7d65, 0x1c375a3a, 
          0x63eb46eb, 0x3f8afc48, 0x4ebb8ae1, 0x3530e006, 
          0x54b566c7, 0x5b7794f4, 0x0a04f41d, 0x71eaf692, 
          0x5f17a863 
};
int ref_4[1] = {
          0x30ae2828 
};
int ref_5[3] = {
          0x4f3756ab, 0x0a3a3108, 0x09e780a1 
};
void func25(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
    check_hash(&b[201], 0x583dedf0, 1, "check_29");
}
void func21(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
    #pragma oss taskwait
    
    #pragma oss task in(b[201;1]) weakinout(all[1;-2]) node(2) wait label("func25")
    func25(b,all);
    
}
void func1(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
    check_hash(&b[192], 0x093f505e, 11, "check_2");
    #pragma oss taskwait noflush
    
    #pragma oss taskwait noflush
    
    #pragma oss task weakinout(all[1;-2]) node(1) label("func21")
    func21(b,all);
    
    #pragma oss task for in(b[198;2]) chunksize(89) node(0) label("taskfor35")
       for(int i=0; i<2; i++) {
            assert(b[198 + i] == ref_0[i]);
            assert( nanos6_get_cluster_node_id() == 0);
    }
}
void func55(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func56(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func58(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func59(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func54(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
    #pragma oss task weakinout(all[1;-2]) node(1) label("func55")
    func55(all);
    
    #pragma oss task weakinout(all[1;-2]) if(0) label("func56")
    func56(all);
    
    #pragma oss task weakinout(all[1;-2]) node(1) label("func58")
    func58(all);
    
    #pragma oss task weakinout(all[1;-2]) if(0) label("func59")
    func59(all);
    
}
void func70(char *all)
{
   assert( nanos6_get_cluster_node_id() == 0);
}
void func73(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func68(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
    #pragma oss task weakinout(all[1;-2]) node(0) wait label("func70")
    func70(all);
    
    #pragma oss task weakinout(all[1;-2]) node(1) label("func73")
    func73(all);
    
}
void func75(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func78(char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
}
void func79(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func81(char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
}
void func74(char *all)
{
   assert( nanos6_get_cluster_node_id() == 0);
    #pragma oss task weakinout(all[1;-2]) node(1) label("func75")
    func75(all);
    
    #pragma oss taskwait noflush
    
    #pragma oss taskwait
    
    #pragma oss task weakinout(all[1;-2]) node(2) wait label("func78")
    func78(all);
    
    #pragma oss task weakinout(all[1;-2]) node(1) wait label("func79")
    func79(all);
    
    #pragma oss task weakinout(all[1;-2]) node(2) label("func81")
    func81(all);
    
}
void func45(char *all)
{
   assert( nanos6_get_cluster_node_id() == 0);
    #pragma oss task weakinout(all[1;-2]) node(1) label("func54")
    func54(all);
    
    #pragma oss task weakinout(all[1;-2]) node(1) wait label("func68")
    func68(all);
    
    #pragma oss task weakinout(all[1;-2]) node(0) wait label("func74")
    func74(all);
    
}
void func0(int *a,int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 0);
    #pragma oss task in(b[192;11]) weakinout(all[1;-2]) node(1) wait label("func1")
    func1(b,all);
    
    #pragma oss task weakinout(all[1;-2]) node(0) wait label("func45")
    func45(all);
    
    #pragma oss taskwait noflush
    
    #pragma oss task for out(a[758;137]) chunksize(105) node(0) label("taskfor83")
       for(int i=0; i<137; i++) {
            a[758+i] = 0xa01ceb8f;
            assert( nanos6_get_cluster_node_id() == 0);
    }
}
void func345(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
    check_hash(&b[818], 0x01537941, 1, "check_424");
}
void func346(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func350(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func351(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
    fill(&b[813], 0x32bb07b1, 1);
}
void func344(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 0);
    check_hash(&b[818], 0x01537941, 1, "check_423");
    #pragma oss task in(b[818;1]) weakinout(all[1;-2]) node(2) wait label("func345")
    func345(b,all);
    
    #pragma oss task weakinout(all[1;-2]) node(1) label("func346")
    func346(all);
    
    #pragma oss taskwait
    
    check_hash(&b[818], 0x01537941, 1, "check_431");
    #pragma oss task weakinout(all[1;-2]) node(1) wait label("func350")
    func350(all);
    
    #pragma oss task out(b[813;1]) weakinout(all[1;-2]) node(1) wait label("func351")
    func351(b,all);
    
}
void func363(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func364(char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func365(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 0);
}
void func367(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
}
void func361(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
    check_hash(&b[818], 0x01537941, 1, "check_446");
    #pragma oss task for in(b[818;1]) chunksize(72) node(1) label("taskfor362")
       for(int i=0; i<1; i++) {
            assert(b[818 + i] == ref_4[i]);
            assert( nanos6_get_cluster_node_id() == 1);
    }
    #pragma oss task weakinout(all[1;-2]) node(1) label("func363")
    func363(b,all);
    
    #pragma oss task weakinout(all[1;-2]) if(0) label("func364")
    func364(all);
    
    #pragma oss task weakinout(all[1;-2]) node(0) label("func365")
    func365(b,all);
    
    #pragma oss taskwait
    
    check_hash(&b[818], 0x01537941, 1, "check_458");
    #pragma oss task weakinout(all[1;-2]) node(2) label("func367")
    func367(b,all);
    
}
void func377(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
    check_hash(&b[818], 0x01537941, 1, "check_476");
}
void func379(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
}
void func380(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
    check_hash(&b[818], 0x01537941, 1, "check_485");
}
void func384(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
}
void func376(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
    check_hash(&b[818], 0x01537941, 1, "check_474");
    #pragma oss task in(b[818;1]) weakinout(all[1;-2]) node(1) wait label("func377")
    func377(b,all);
    
    #pragma oss taskwait noflush
    
    #pragma oss taskwait
    
    check_hash(&b[818], 0x01537941, 1, "check_480");
    #pragma oss task weakinout(all[1;-2]) node(2) wait label("func379")
    func379(b,all);
    
    #pragma oss task in(b[818;1]) weakinout(all[1;-2]) if(0) label("func380")
    func380(b,all);
    
    #pragma oss task weakinout(all[1;-2]) node(2) label("func384")
    func384(b,all);
    
}
void func343(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
    check_hash(&b[818], 0x01537941, 1, "check_421");
    #pragma oss task in(b[818;1]) out(b[813;1]) weakinout(all[1;-2]) node(0) label("func344")
    func344(b,all);
    
    #pragma oss task in(b[818;1]) weakinout(all[1;-2]) node(1) wait label("func361")
    func361(b,all);
    
    #pragma oss taskwait noflush
    
    #pragma oss task in(b[818;1]) weakinout(all[1;-2]) node(2) wait label("func376")
    func376(b,all);
    
}
void func429(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 0);
}
void func430(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
}
void func432(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
}
void func426(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 1);
    check_hash(&b[728], 0x57bbe089, 1, "check_538");
    #pragma oss taskwait noflush
    
    #pragma oss task weakinout(all[1;-2]) node(0) label("func429")
    func429(b,all);
    
    #pragma oss task weakinout(all[1;-2]) if(0) label("func430")
    func430(b,all);
    
    #pragma oss task for out(b[721;3]) chunksize(50) node(1) label("taskfor431")
       for(int i=0; i<3; i++) {
            b[721+i] = 0x8f00854f;
            assert( nanos6_get_cluster_node_id() == 1);
    }
    #pragma oss task weakinout(all[1;-2]) node(2) wait label("func432")
    func432(b,all);
    
}
void func385(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
    fill(&b[726], 0x2df60a42, 5);
    #pragma oss task inout(b[728;1]) out(b[712;13]) weakinout(all[1;-2]) node(1) label("func426")
    func426(b,all);
    
}
void func205(int *b,char *all)
{
   assert( nanos6_get_cluster_node_id() == 2);
    fill(&b[926], 0x4bcb3678, 1);
    #pragma oss task for out(b[923;1]) chunksize(65) node(2) label("taskfor253")
       for(int i=0; i<1; i++) {
            b[923+i] = 0xaf35f7e5;
            assert( nanos6_get_cluster_node_id() == 2);
    }
    #pragma oss task for inout(b[561;105]) chunksize(41) node(2) label("taskfor255")
       for(int i=0; i<105; i++) {
            assert(b[561 + i] == ref_3[i]);
            b[561+i] ^= 0xb590b9f2;
            assert( nanos6_get_cluster_node_id() == 2);
    }
    #pragma oss task in(b[818;1]) weakinout(all[1;-2]) node(2) label("func343")
    func343(b,all);
    
    #pragma oss task out(b[689;42]) weakinout(all[1;-2]) node(2) label("func385")
    func385(b,all);
    
}

int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));
	char *all = (char *)NULL;


	pthread_t watchdog;
	if (pthread_create(&watchdog, NULL, watchdog_func, NULL)) {
		return 1;
	}
    fill(&b[0], 0xe6e5b70a, 1000);

    #pragma oss task out(a[492;478]) weakinout(all[1;-2]) node(0) label("func0")
    func0(a,b,all);
    
    #pragma oss taskwait noflush
    
    #pragma oss taskwait
    
    check_hash(&b[0], 0x66149ca4, 228, "check_273");
    check_hash(&b[231], 0x2af0e002, 769, "check_273");
    #pragma oss task out(b[910;20]) weakinout(all[1;-2]) node(2) wait label("func205")
    func205(b,all);
    
    #pragma oss taskwait
    
    check_hash(&b[0], 0x4b182c9b, 97, "check_642");
    check_hash(&b[160], 0x5c552664, 52, "check_642");
    check_hash(&b[217], 0x00003039, 2, "check_642");
    check_hash(&b[220], 0x6ea1ed80, 8, "check_642");
    check_hash(&b[231], 0x5c7b92e7, 127, "check_642");
    check_hash(&b[541], 0x744977fc, 24, "check_642");
    check_hash(&b[567], 0x0bb7c3c5, 15, "check_642");
    check_hash(&b[590], 0x61b8c300, 72, "check_642");
    check_hash(&b[664], 0x2890f5e3, 5, "check_642");
    check_hash(&b[670], 0x5b332510, 3, "check_642");
    check_hash(&b[798], 0x18eac4d1, 13, "check_642");
    check_hash(&b[818], 0x08365b08, 92, "check_642");
    check_hash(&b[923], 0x6ba082ba, 1, "check_642");
    check_hash(&b[930], 0x1e0a46d1, 70, "check_642");

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));
     watchdog_done = 1;
    pthread_join(watchdog, NULL);

    printf("Test passed [/home/bsc28/bsc28600/work/20210906-impi/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 500 --nesting 4 --seed 1427 --watchdog 45 --auto --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
