// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 1000 --nesting 4 --seed 18 --enable-file ../ompss-2-testgen/simplest.txt --no-hash --track a[923]
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//01000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00010000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000011000100011000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//0000000000000000000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>

void show(const int *a, int n)
{
	printf("Show %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		printf("0x%08x\n", a[j]);
	}
}

void check(const int *a, const int *ref, int n, const char *name, int ofs)
{
	// printf("Check %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		if (a[j] != ref[j])
		{
			const char *eq = (a[j] == ref[j]) ? "==" : "!=";
			printf("%s[%d]: 0x%08x %s 0x%08x\n", name, ofs+j, a[j], eq, ref[j]);
			assert_that(a[j] == ref[j]);
		}
	}
}

void copy(int *a, const int *ref, int n)
{
	memcpy(a, ref, n * sizeof(int));
}

void check_hash(const int *a, int hash, int n, const char *name)
{
	int val = 0;
	for (int j=0; j<n; j++)
	{
		val ^= a[j];
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
	if (val != hash)
		printf("Error in %s\n", name);
	assert_that(val == hash);
}

void fill(int *a, int val, int n)
{
	for (int j=0; j<n; j++)
	{
		a[j] = val;
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
}


int out_0[1] = {
          0xc17faaf5 
};
int out_1[1] = {
          0x05a9b343 
};
void func739(int *a)
{
   assert_that( nanos6_get_cluster_node_id() == 2);
    check(&a[923], out_0, 1, "check_1427 a", 923);
    copy(&a[923], out_1, 1);
}
void func735(int *a)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    check(&a[923], out_0, 1, "check_1416 a", 923);
    #pragma oss task inout(a[923;1]) node(2)
    func739(a);
    
}
void func734(int *a)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check(&a[923], out_0, 1, "check_1414 a", 923);
    #pragma oss task inout(a[923;1]) node(0)
    func735(a);
    
    #pragma oss taskwait noflush
    
    #pragma oss taskwait
    
    check(&a[923], out_1, 1, "check_1434 a", 923);
}
void func518(int *a)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    check(&a[923], out_0, 1, "check_961 a", 923);
    #pragma oss task inout(a[923;1]) node(1)
    func734(a);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss taskwait on(a[923;1])
    
    copy(&a[923], out_0, 1);
    #pragma oss task inout(a[923;1]) node(0)
    func518(a);
    
    #pragma oss taskwait

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 1000 --nesting 4 --seed 18 --enable-file ../ompss-2-testgen/simplest.txt --no-hash --track a[923]]\n");
	
    return(0);
}
	
