// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 200 --nesting 3 --seed 14 --no-taskwaitnoflush --watchdog 15 --enable-file noflush_fail8-control.txt --no-hash --track b[574]
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000001000000
//0000000000000000001000000100000001011000000000000000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>

int watchdog_done = 0;
void *watchdog_func(void *x)
{
	for(int j=0;j<15;j++) {
		sleep(1);
		if (watchdog_done) {
			return NULL;
		}
	}
	printf("Watchdog timer expired (15 seconds)\n");
	exit(1);
}


void show(const int *a, int n)
{
	printf("Show %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		printf("0x%08x\n", a[j]);
	}
}

void check(const int *a, const int *ref, int n, const char *name, int ofs)
{
	// printf("Check %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		if (a[j] != ref[j])
		{
			const char *eq = (a[j] == ref[j]) ? "==" : "!=";
			printf("%s[%d]: 0x%08x %s 0x%08x\n", name, ofs+j, a[j], eq, ref[j]);
			assert_that(a[j] == ref[j]);
		}
	}
}

void copy(int *a, const int *ref, int n)
{
	memcpy(a, ref, n * sizeof(int));
}

void check_hash(const int *a, int hash, int n, const char *name)
{
	int val = 0;
	for (int j=0; j<n; j++)
	{
		val ^= a[j];
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
	if (val != hash)
		printf("Error in %s\n", name);
	assert_that(val == hash);
}

void fill(int *a, int val, int n)
{
	for (int j=0; j<n; j++)
	{
		a[j] = val;
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
}


int out_0[1] = {
          0x9dc55079 
};
int out_1[1] = {
          0xddb1e263 
};
int out_2[1] = {
          0x83c68b8b 
};
void func157(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check(&b[574], out_1, 1, "check_283 b", 574);
    copy(&b[574], out_2, 1);
}
void func151(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check(&b[574], out_1, 1, "check_272 b", 574);
    #pragma oss task inout(b[574;5]) node(1)
    func157(b);
    
}
void func167(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
}
void func165(int *b)
{
    #pragma oss task weakin(b[537;38]) node(1)
    func167(b);
    
    #pragma oss taskwait
    
}
void func129(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    copy(&b[574], out_1, 1);
    #pragma oss task inout(b[551;89]) node(1)
    func151(b);
    
    #pragma oss task weakin(b[533;46]) weakout(b[579;375]) if(0)
    func165(b);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));


	pthread_t watchdog;
	if (pthread_create(&watchdog, NULL, watchdog_func, NULL)) {
		return 1;
	}
    copy(&b[574], out_0, 1);

    #pragma oss task weakout(a[185;528]) out(b[184;816]) node(0)
    func129(a,b);
    
    #pragma oss taskwait
    
    check(&b[574], out_2, 1, "check_362 b", 574);

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));
     watchdog_done = 1;
    pthread_join(watchdog, NULL);

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 200 --nesting 3 --seed 14 --no-taskwaitnoflush --watchdog 15 --enable-file noflush_fail8-control.txt --no-hash --track b[574]]\n");
	
    return(0);
}
	
