// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 65 --nesting 3 --seed 10 --taskwaitnoflush --no-hash --track a[822]

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>

void func40(int *a)
{
    a[822] = 2;
}

void func39(int *a)
{
    a[822] = 1;
    #pragma oss task inout(a[822;1]) node(0)
    func40(a);
    
    #pragma oss taskwait noflush
    
    #pragma oss taskwait
    
    assert_that(a[822] == 2);
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task inout(a[821;2]) inout(a[823;2]) node(1)
    func39(a);
    
    #pragma oss taskwait
    
    nanos6_dfree(a, 1000 * sizeof(int));
    nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 65 --nesting 3 --seed 10 --taskwaitnoflush --no-hash --track a[822]]\n");
	
    return(0);
}
	
