// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 500 --nesting 4 --seed 18 --no-taskwaitnoflush --enable-file control.txt --no-hash --track b[470]

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>

void show(const int *a, int n)
{
	printf("Show %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		printf("0x%08x\n", a[j]);
	}
}

void check(const int *a, const int *ref, int n, const char *name, int ofs)
{
	// printf("Check %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		if (a[j] != ref[j])
		{
			const char *eq = (a[j] == ref[j]) ? "==" : "!=";
			printf("%s[%d]: 0x%08x %s 0x%08x\n", name, ofs+j, a[j], eq, ref[j]);
			assert_that(a[j] == ref[j]);
		}
	}
}

void copy(int *a, const int *ref, int n)
{
	memcpy(a, ref, n * sizeof(int));
}

void check_hash(const int *a, int hash, int n, const char *name)
{
	int val = 0;
	for (int j=0; j<n; j++)
	{
		val ^= a[j];
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
	if (val != hash)
		printf("Error in %s\n", name);
	assert_that(val == hash);
}

void fill(int *a, int val, int n)
{
	for (int j=0; j<n; j++)
	{
		a[j] = val;
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
}


int out_0[1] = {
          0x626cf56e 
};
int out_1[1] = {
          0xf8034593 
};
void func157(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    check(&b[470], out_0, 1, "check_299 b", 470);
    copy(&b[470], out_1, 1);
}
void func156(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check(&b[470], out_0, 1, "check_296 b", 470);
    #pragma oss task inout(b[456;25]) node(0)
    func157(b);
    
    #pragma oss taskwait noflush
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    copy(&b[470], out_0, 1);

    #pragma oss task out(b[713;281]) inout(b[417;191]) weakout(a[951;9]) node(1)
    func156(a,b);
    
    #pragma oss taskwait
    
    check(&b[470], out_1, 1, "check_966 b", 470);

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 500 --nesting 4 --seed 18 --no-taskwaitnoflush --enable-file control.txt --no-hash --track b[470]]\n");
	
    return(0);
}
	
