// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 1 --tasks 75 --nesting 2 --seed 1 --enable-file simplify-control.txt

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>

void show(const int *a, int n)
{
	printf("Show %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		printf("0x%08x\n", a[j]);
	}
}

void check(const int *a, const int *ref, int n, const char *name, int ofs)
{
	// printf("Check %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		if (a[j] != ref[j])
		{
			const char *eq = (a[j] == ref[j]) ? "==" : "!=";
			printf("%s[%d]: 0x%08x %s 0x%08x\n", name, ofs+j, a[j], eq, ref[j]);
			assert_that(a[j] == ref[j]);
		}
	}
}

void copy(int *a, const int *ref, int n)
{
	memcpy(a, ref, n * sizeof(int));
}

void check_hash(const int *a, int hash, int n, const char *name)
{
	int val = 0;
	for (int j=0; j<n; j++)
	{
		val ^= a[j];
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
	if (val != hash)
		printf("Error in %s\n", name);
	assert_that(val == hash);
}

void fill(int *a, int val, int n)
{
	for (int j=0; j<n; j++)
	{
		a[j] = val;
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
}


void func31(int *a)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    fill(&a[839], 0x2ff843e4, 32);
}
void func37(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    fill(&b[781], 0x5dcf3167, 12);
    fill(&a[517], 0x8f82efb5, 42);
}
void func30(int *a,int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    #pragma oss task out(a[839;32]) node(0)
    func31(a);
    
    #pragma oss taskwait noflush
    
    #pragma oss taskwait on(a[537;59])
    
    fill(&a[537], 0x63841ea9, 59);
    fill(&b[775], 0xf816ebc7, 12);
    #pragma oss task weakout(a[866;76]) out(b[781;12]) out(a[517;42]) weakinout(a[568;7]) node(0)
    func37(a,b);
    
}
void func51(int *a)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    fill(&a[41], 0xf40a729d, 1);
}
void func52(int *a)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
}
void func58(int *a)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
}
void func50(int *a)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    #pragma oss task out(a[41;1]) node(0)
    func51(a);
    
    #pragma oss task weakout(a[52;4]) node(0)
    func52(a);
    
    fill(&a[42], 0x222a9fe1, 7);
    #pragma oss task weakin(a[42;7]) weakout(a[53;3]) node(0)
    func58(a);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    fill(&b[0], 0x55dbc5a7, 1000);

    #pragma oss taskwait
    
    fill(&b[992], 0x96ef420b, 7);
    #pragma oss task out(b[734;62]) weakout(a[461;195]) out(a[796;187]) node(0)
    func30(a,b);
    
    fill(&b[230], 0xd10f68e3, 472);
    #pragma oss task weakout(a[260;579]) out(a[30;28]) node(0)
    func50(a);
    
    #pragma oss taskwait
    
    check_hash(&b[230], 0x60e0e728, 13, "check_110");
    check_hash(&b[267], 0x720723c0, 40, "check_110");
    check_hash(&b[489], 0x75621739, 10, "check_110");
    check_hash(&b[521], 0x00003039, 2, "check_110");
    check_hash(&b[647], 0x5ebaab00, 8, "check_110");
    check_hash(&b[674], 0x74a0854d, 3, "check_110");
    check_hash(&b[698], 0x0925d0ec, 4, "check_110");
    check_hash(&b[992], 0x7e53a079, 7, "check_110");

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 1 --tasks 75 --nesting 2 --seed 1 --enable-file simplify-control.txt]\n");
	
    return(0);
}
	
