/*
 * Copyright (C) 2022  Paul Capenter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 45 --nesting 5 --seed 2 --watchdog 45 --taskfor --enable-file .simplify/simplify-control.txt
//11000000000000000000000000000000000000000000000000000101000000000000000000000000
//


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>


int main(void)
{
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task for inout(b[614;110]) chunksize(5) label("taskfor1")
       for(int i=0; i<110; i++) {
            b[614+i] = 0x8df3e568;
    }
    #pragma oss taskwait
    
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 45 --nesting 5 --seed 2 --watchdog 45 --taskfor --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
