// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --no-hash --nodes 3 --tasks 80 --nesting 5 --seed 9 --watchdog 45 --taskfor --enable-file .simplify/simplify-control.txt
//00010000000000000000000000000000000000000000000000000000000000000000000110110000
//0000100000000101000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void func72(int *b)
{
}
void func70(int *b)
{
    #pragma oss task in(b[657;1]) in(b[658;1]) node(0) label("func72")
    func72(b);
}
void func56(int *b)
{
    #pragma oss taskwait on(b[657;1])
    
    #pragma oss task for out(b[658;1]) chunksize(3) label("taskfor63")
       for(int i=0; i<1; i++) {
            b[658+i] = 0x023be682;
    }
    #pragma oss task inout(b[657;1]) weakin(b[658;1]) node(1) wait label("func70")
    func70(b);
    
}
void func55(int *b)
{
    #pragma oss taskwait
    
    #pragma oss task inout(b[657;2]) inout(b[660;1]) if(0) label("func56")
    func56(b);
    
}
void func1(int *b)
{
    #pragma oss task in(b[584;21]) weakinout(b[638;25]) node(2) wait label("func55")
    func55(b);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

	printf("Starting taskfor11\n");

    #pragma oss task weakinout(b[434;234]) inout(b[668;88]) out(b[92;194]) if(0) label("func1")
    func1(b);
    
    #pragma oss taskwait
    

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --no-hash --nodes 3 --tasks 80 --nesting 5 --seed 9 --watchdog 45 --taskfor --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
