/*
 * Copyright (C) 2022  Paul Capenter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 95 --nesting 2 --seed 18 --no-hash --enable-file ../ompss-2-testgen/simplest.txt --track b[753]
//10000000001001000000000000010000000000000000000000000000000000000000000000000000
//0000000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void show(const int *a, int n)
{
	printf("Show %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		printf("0x%08x\n", a[j]);
	}
}

void check(const int *a, const int *ref, int n, const char *name, int ofs)
{
	// printf("Check %p size %d\n", a, n);
	for (int j=0; j<n; j++)
	{
		if (a[j] != ref[j])
		{
			const char *eq = (a[j] == ref[j]) ? "==" : "!=";
			printf("%s[%d]: 0x%08x %s 0x%08x\n", name, ofs+j, a[j], eq, ref[j]);
			assert_that(a[j] == ref[j]);
		}
	}
}

void copy(int *a, const int *ref, int n)
{
	memcpy(a, ref, n * sizeof(int));
}

void check_hash(const int *a, int hash, int n, const char *name)
{
	int val = 0;
	for (int j=0; j<n; j++)
	{
		val ^= a[j];
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
	if (val != hash)
		printf("Error in %s\n", name);
	assert_that(val == hash);
}

void fill(int *a, int val, int n)
{
	for (int j=0; j<n; j++)
	{
		a[j] = val;
		val = ((val * 1103515245) + 12345) & 0x7fffffff;
	}
}


int out_0[1] = {
          0x626cf56e 
};
int out_1[1] = {
          0x64cf0553 
};
void func9(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 1);
    check(&b[753], out_0, 1, "check_19 b", 753);
    copy(&b[753], out_1, 1);
}

void func22(int *b)
{
   assert_that( nanos6_get_cluster_node_id() == 0);
    check(&b[753], out_1, 1, "check_46 b", 753);
}

bool taskwait_noflush3()
{
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    copy(&b[753], out_0, 1);

    #pragma oss task inout(b[753;1]) node(1)
    func9(b);
    
    #pragma oss taskwait noflush
    
    #pragma oss task inout(b[668;96]) node(0)
    func22(b);
    
    #pragma oss taskwait
    
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 95 --nesting 2 --seed 18 --no-hash --enable-file ../ompss-2-testgen/simplest.txt --track b[753]]\n");
	
    return true;
}
	
int main(int argc, char *argv[])
{
	test_t test = FUNC_DEF(taskwait_noflush3);

	return run_test(&test);
}
