// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 65 --nesting 2 --seed 14 --watchdog 25 --enable-file .simplify/simplify-control.txt
//000000000000000000000001000001000100000000000000000000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>


void func22(int *b)
{
}
void func26(int *b)
{
}
void func18(int *b)
{
    #pragma oss task weakinout(b[204;8]) node(0) wait label("func22")
    func22(b);
    
    #pragma oss task in(b[204;8]) node(1) label("func26")
    func26(b);
    
}


int main(void)
{
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task out(b[204;8]) node(2) wait label("func18")
    func18(b);
    
    #pragma oss taskwait

   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 65 --nesting 2 --seed 14 --watchdog 25 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
