/*
 * Copyright (C) 2022  Paul Capenter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


// Generated by /home/bsc28/bsc28600/work/20210906-impi/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 500 --nesting 5 --seed 10 --watchdog 30 --no-all-region --no-hash --enable-file .simplify/simplest.txt
//00110000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000010000000000000000000000000000000000000000
//00000000100000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000010110
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000001000000000000000000000000000000000000000000000000000000000000000
//000000111000000000000000000000000000000000000000000000100000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void func348(int *b)
{
    #pragma oss task in(b[732;5]) node(0) label("func411")
	{
    }
}
void func458(int *a,int *b)
{
    #pragma oss task out(b[732;31]) node(1) label("func488")
     {
		b[736] = 0x68050697; // this is the write
    }
}
void func457(int *a,int *b)
{
    #pragma oss task weakout(b[697;92]) node(1) label("func458")
    func458(a,b);
}

int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

	b[736] = 0x7aa00d4f;

    #pragma oss task in(b[731;6]) node(1) label("func348")
    func348(b);
    
    #pragma oss task weakinout(b[594;240]) node(1) wait label("func457")
    func457(a,b);
    
    #pragma oss taskwait
	printf("Get b[736] = %x\n", b[736]);
	assert_that(b[736] == 0x68050697);

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20210906-impi/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 500 --nesting 5 --seed 10 --watchdog 30 --no-all-region --no-hash --enable-file .simplify/simplest.txt]\n");
	
    return(0);
}
	
