// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 60 --nesting 2 --seed 12 --watchdog 45 --enable-file .simplify/simplify-control.txt
//000000010000000000000010010000011000000000010000111000100000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>

void func27(int *a)
{
}
void func40(int *a)
{
}
void func41(int *a)
{
}
void func36(int *a)
{
    #pragma oss task in(a[916;40]) node(0) label("func40")
    func40(a);
    
    #pragma oss task weakin(a[916;40]) node(0) wait label("func41")
    func41(a);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task in(a[906;37]) node(1) label("func27")
    func27(a);
    
    #pragma oss task weakin(a[916;40]) node(2) wait label("func36")
    func36(a);
    
    #pragma oss taskwait

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 60 --nesting 2 --seed 12 --watchdog 45 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
