// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 1000 --nesting 3 --seed 13 --watchdog 25 --taskfor --enable-file .simplify/simplify-control.txt
//10000000000000000010100100101000101100111110000000010100101100111000000000000000
//00011111001001000101011111110101110010000000000000000000000000000000000100000000
//00000000011000110110001011111011111100011100000000110011011101101111000000000000
//00001001100100111001011111110111000100000000000000000000000000000000000000000000
//01111100111011101100000000000000000000000000000000000000000000000001100010101100
//00101001100101100001100110000000000000000000000000000000000000000000000000000001
//11010111100111000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000010000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//00000000000000000000000000000000000000000000000000000000000000000000000000000000
//000000000000000000000000000000000000000000000000000000000000000

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>

void func22()
{
}
void func24()
{
}
void func28()
{
}
void func16()
{
    #pragma oss taskwait
    
    #pragma oss task  if(0) label("func22")
    func22();
    
    #pragma oss task  node(2) wait label("func24")
    func24();
    
    #pragma oss task  node(0) wait label("func28")
    func28();
    
}
void func31()
{
}
void func34()
{
}
void func37()
{
}
void func30(int *b)
{
    #pragma oss task  node(2) label("func31")
    func31();
    
    #pragma oss task  if(0) label("func34")
    func34();
    
    #pragma oss taskwait
    
    #pragma oss task  node(1) wait label("func37")
    func37();
    
}
void func48(int *b)
{
}
void func51()
{
}
void func52()
{
}
void func55(int *b)
{
}
void func56()
{
}
void func57()
{
}
void func46(int *b)
{
    #pragma oss task weakout(b[404;21]) node(1) wait label("func48")
    func48(b);
    
    #pragma oss task  node(2) label("func51")
    func51();
    
    #pragma oss taskwait
    
    #pragma oss task  node(0) label("func52")
    func52();
    
    #pragma oss task weakout(b[312;65]) node(2) wait label("func55")
    func55(b);
    
    #pragma oss task  if(0) label("func56")
    func56();
    
    #pragma oss task  node(0) wait label("func57")
    func57();
    
}
void func77()
{
}
void func80()
{
}
void func87()
{
}
void func89()
{
}
void func91()
{
}
void func75(int *b)
{
    #pragma oss taskwait noflush
    
    #pragma oss task  node(0) wait label("func77")
    func77();
    
    #pragma oss taskwait noflush
    
    #pragma oss task  node(0) label("func80")
    func80();
    
    #pragma oss task  node(0) wait label("func87")
    func87();
    
    #pragma oss task  node(1) wait label("func89")
    func89();
    
    #pragma oss task  if(0) label("func91")
    func91();
    
}
void func94()
{
}
void func95(int *b)
{
}
void func97(int *b)
{
}
void func99()
{
}
void func100(int *b)
{
}
void func93(int *b)
{
    #pragma oss task  node(2) wait label("func94")
    func94();
    
    #pragma oss taskwait
    
    #pragma oss taskwait noflush
    
    #pragma oss task weakout(b[311;2]) node(2) wait label("func95")
    func95(b);
    
    #pragma oss task weakout(b[250;1]) out(b[311;8]) node(1) label("func97")
    func97(b);
    
    #pragma oss task  node(0) label("func99")
    func99();
    
    #pragma oss task out(b[323;2]) node(2) wait label("func100")
    func100(b);
    
}
void func0(int *a,int *b)
{
    #pragma oss task  node(0) wait label("func16")
    func16();
    
    #pragma oss task out(b[389;34]) node(1) wait label("func30")
    func30(b);
    
    #pragma oss task weakout(b[285;140]) node(1) label("func46")
    func46(b);
    
    #pragma oss task weakout(b[366;25]) node(2) wait label("func75")
    func75(b);
    
    #pragma oss task weakout(b[243;17]) weakout(b[311;15]) node(1) wait label("func93")
    func93(b);
    
}
void func157()
{
}
void func161()
{
}
void func163()
{
}
void func164()
{
}
void func165()
{
}
void func155()
{
    #pragma oss taskwait noflush
    
    #pragma oss taskwait
    
    #pragma oss task  node(2) wait label("func157")
    func157();
    
    #pragma oss task  node(2) label("func161")
    func161();
    
    #pragma oss task  node(0) wait label("func163")
    func163();
    
    #pragma oss task  node(1) label("func164")
    func164();
    
    #pragma oss task  node(0) label("func165")
    func165();
    
}
void func167()
{
}
void func169()
{
}
void func171()
{
}
void func172()
{
}
void func173()
{
}
void func176()
{
}
void func177()
{
}
void func166()
{
    #pragma oss task  node(1) wait label("func167")
    func167();
    
    #pragma oss task  if(0) label("func169")
    func169();
    
    #pragma oss task  node(0) wait label("func171")
    func171();
    
    #pragma oss task  node(1) label("func172")
    func172();
    
    #pragma oss taskwait
    
    #pragma oss task  node(2) label("func173")
    func173();
    
    #pragma oss task  node(1) wait label("func176")
    func176();
    
    #pragma oss task  node(0) wait label("func177")
    func177();
    
}
void func186()
{
}
void func187()
{
}
void func178()
{
    #pragma oss task  node(1) wait label("func186")
    func186();
    
    #pragma oss task  node(1) label("func187")
    func187();
    
}
void func191()
{
}
void func193()
{
}
void func196()
{
}
void func197()
{
}
void func199()
{
}
void func200()
{
}
void func190()
{
    #pragma oss task  node(2) wait label("func191")
    func191();
    
    #pragma oss task  node(1) label("func193")
    func193();
    
    #pragma oss taskwait
    
    #pragma oss task  node(0) wait label("func196")
    func196();
    
    #pragma oss task  node(1) wait label("func197")
    func197();
    
    #pragma oss task  node(1) wait label("func199")
    func199();
    
    #pragma oss task  node(1) label("func200")
    func200();
    
}
void func221()
{
}
void func228()
{
}
void func229()
{
}
void func232()
{
}
void func219()
{
    #pragma oss task  node(2) label("func221")
    func221();
    
    #pragma oss taskwait noflush
    
    #pragma oss task  node(1) label("func228")
    func228();
    
    #pragma oss task  node(2) wait label("func229")
    func229();
    
    #pragma oss task  node(0) wait label("func232")
    func232();
    
}
void func235()
{
}
void func236()
{
}
void func237()
{
}
void func238()
{
}
void func240()
{
}
void func246()
{
}
void func234()
{
    #pragma oss taskwait noflush
    
    #pragma oss task  node(2) wait label("func235")
    func235();
    
    #pragma oss taskwait
    
    #pragma oss task  node(2) wait label("func236")
    func236();
    
    #pragma oss task  node(1) wait label("func237")
    func237();
    
    #pragma oss task  node(2) wait label("func238")
    func238();
    
    #pragma oss task  node(0) wait label("func240")
    func240();
    
    #pragma oss task  node(0) label("func246")
    func246();
    
}
void func152(int *a)
{
    #pragma oss taskwait
    
    #pragma oss task  node(1) label("func155")
    func155();
    
    #pragma oss task  node(1) label("func166")
    func166();
    
    #pragma oss task  node(1) wait label("func178")
    func178();
    
    #pragma oss task  node(0) label("func190")
    func190();
    
    #pragma oss task  node(2) label("func219")
    func219();
    
    #pragma oss task  node(2) label("func234")
    func234();
    
}
void func292(int *b)
{
}
void func293(int *b)
{
}
void func295()
{
}
void func296(int *b)
{
}
void func297()
{
}
void func299()
{
}
void func300()
{
}
void func287(int *b)
{
    #pragma oss taskwait noflush
    
    #pragma oss task for out(b[624;4]) chunksize(3) label("taskfor291")
       for(int i=0; i<4; i++) {
            b[624+i] = 0xc49c0c06;
    }
    #pragma oss task weakout(b[628;3]) node(2) label("func292")
    func292(b);
    
    #pragma oss task weakout(b[626;3]) node(2) label("func293")
    func293(b);
    
    #pragma oss task  node(0) label("func295")
    func295();
    
    #pragma oss task weakinout(b[624;2]) weakout(b[628;1]) node(2) label("func296")
    func296(b);
    
    #pragma oss task  node(1) wait label("func297")
    func297();
    
    #pragma oss task  node(1) wait label("func299")
    func299();
    
    #pragma oss task  if(0) label("func300")
    func300();
    
}
void func350(int *a)
{
}
void func358()
{
}
void func360()
{
}
void func345(int *a)
{
    #pragma oss taskwait
    
    #pragma oss task weakin(a[929;1]) node(1) label("func350")
    func350(a);
    
    #pragma oss task for inout(a[926;1]) chunksize(32) label("taskfor353")
       for(int i=0; i<1; i++) {
            a[926+i] ^= 0x999b1b5d;
    }
    #pragma oss task  node(1) wait label("func358")
    func358();
    
    #pragma oss task  node(1) wait label("func360")
    func360();
    
}
void func365()
{
}
void func367()
{
}
void func368()
{
}
void func373()
{
}
void func374()
{
}
void func378()
{
}
void func364()
{
    #pragma oss task  if(0) label("func365")
    func365();
    
    #pragma oss task  node(2) label("func367")
    func367();
    
    #pragma oss task  node(1) wait label("func368")
    func368();
    
    #pragma oss task  node(2) wait label("func373")
    func373();
    
    #pragma oss task  node(2) wait label("func374")
    func374();
    
    #pragma oss task  node(0) label("func378")
    func378();
    
}
void func432()
{
}
void func436(int *b)
{
}
void func438()
{
}
void func441(int *b)
{
}
void func442(int *b)
{
}
void func443(int *b)
{
}
void func431(int *b)
{
    #pragma oss task  node(0) label("func432")
    func432();
    
    #pragma oss task weakout(b[623;1]) node(2) wait label("func436")
    func436(b);
    
    #pragma oss taskwait noflush
    
    #pragma oss task for in(b[618;5]) chunksize(3) label("taskfor437")
       for(int i=0; i<5; i++) {
    }
    #pragma oss task  node(1) label("func438")
    func438();
    
    #pragma oss task weakin(b[615;5]) out(b[620;5]) node(0) wait label("func441")
    func441(b);
    
    #pragma oss task inout(b[610;10]) if(0) label("func442")
    func442(b);
    
    #pragma oss task weakout(b[594;33]) node(1) label("func443")
    func443(b);
    
}
void func286(int *a,int *b)
{
    #pragma oss taskwait on(a[925;7])
    
    #pragma oss task weakout(b[624;7]) node(1) label("func287")
    func287(b);
    
    #pragma oss task inout(a[925;7]) node(0) label("func345")
    func345(a);
    
    #pragma oss task  node(0) wait label("func364")
    func364();
    
    #pragma oss task out(b[590;37]) node(2) label("func431")
    func431(b);
    
}


int main(void)
{
	int *a = nanos6_dmalloc(1000 * sizeof(int), nanos6_equpart_distribution, 0, NULL);
	int *b = nanos6_lmalloc(1000 * sizeof(int));


    // #pragma oss task weakout(a[791;24]) out(b[138;287]) if(0) label("func0")
    func0(a,b);
    
    #pragma oss task out(a[702;145]) node(2) wait label("func152")
    func152(a);
    
    // #pragma oss task weakout(b[511;134]) weakout(a[668;280]) if(0) label("func286")
    func286(a,b);
    
    #pragma oss taskwait
    
    #pragma oss taskwait

   nanos6_dfree(a, 1000 * sizeof(int));
   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 1000 --nesting 3 --seed 13 --watchdog 25 --taskfor --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
