// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 65 --nesting 3 --seed 10 --taskwaitnoflush --no-hash --track a[822]

#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>


void func40(int *a)
{
    a[822] = 2;
}

void func39(int *a)
{
    a[822] = 1;
    #pragma oss task inout(a[822;1]) node(0) label("func40")
    func40(a);
    
    #pragma oss taskwait noflush
    
    #pragma oss taskwait
    
    assert_that(a[822] == 2);
}

bool taskwait_noflush2()
{
	int *a = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task inout(a[822;1]) node(1) label("func39")
    func39(a);
    
    #pragma oss taskwait
    
    nanos6_lfree(a, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 2 --tasks 65 --nesting 3 --seed 10 --taskwaitnoflush --no-hash --track a[822]]\n");
	
    return true;
}
	
int main(int argc, char *argv[])
{
	test_t test = FUNC_DEF(taskwait_noflush2);

	return run_test(&test);
}
