// Generated by /home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 65 --nesting 2 --seed 14 --watchdog 25 --enable-file .simplify/simplify-control.txt
//000000000000000000000001000001000100000000000000000000000000000000000000000000


#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <nanos6.h>
#include <unistd.h>
#include <pthread.h>



int main(void)
{
	int *b = nanos6_lmalloc(1000 * sizeof(int));

    #pragma oss task out(b[0;1000]) node(2) label("init")
    {
		sleep(1);
	}

	#pragma oss task weakin(b[0;1000]) node(0) label("task0")
	{
		for(int j=0; j<50; j++) {
			#pragma oss task in(b[0;1000]) node(0) label("task1")
			{
				sleep(1);
			}
		}
	}
    
    #pragma oss taskwait

   nanos6_lfree(b, 1000 * sizeof(int));

    printf("Test passed [/home/bsc28/bsc28600/work/20201023-experimental/ompss-2-testgen/ompss-2-testgen --nodes 3 --tasks 65 --nesting 2 --seed 14 --watchdog 25 --enable-file .simplify/simplify-control.txt]\n");
	
    return(0);
}
	
